### ISSUE TITLE
operator can steal utxo, after finalizes ife

### ISSUE THREAD

**Issue by pthomalla** [omisego/plasma-contracts#104]
## Issue Type 

```
[x] bug report
[ ] feature request
```
## Current Behavior

Operator can steal funds from root chain account.

## Steps to Reproduce

1. Operator creates two transactions `tx1` and `tx2` double-spending shared input `a`
2. Operator create IFE from transaction`tx1` and doesn't include it in block
3. IFE finalizes
4. Operator creates a block that includes `tx2`
5. Operator create IFE from transaction `tx2`
6. During period 1 other player challenges canonicity of `tx2`
7. Operator responds to challege by providing inclusion proofs.

Second double spend IFE exiting with high priority (priority of input `a`)

## Suggested Fix

in function `_processInFlightExit` check `inputs` of canonical IFE transaction in `exits`  (mapping from contract)
 1. if all `inputs` aren't in exits, add `inputs` to `exits` and IFE stay canonical
 2. otherwise IFE transactions become non-canonical

**Comment by boolafish** [comment]
I’d like to propose to make input finalized as a condition for non-canonical challenge instead. Basically that means input is used.

Current proposal does not fit well for large input/output transaction. (Well...we don’t have this concern at this moment and probably we would just use MVP for large tx but.....)

**Comment by pdobacz** [comment]
just bookkeeping: similar issue to #102, and chances are both can be solved by the same proposition (one discussed with @pnowosie & @pthomalla, will be hashed out and written down somewhere at some point)

**Comment by boolafish** [comment]
[note]
[Kelvin's solution](https://github.com/omisego/plasma-contracts/issues/102#issuecomment-495809967) in #102 would solve this one. IFE of tx2 basically would just not be processed with fund transfer. (btw, it's more or less the same as the proposed solution in the description)

**Comment by boolafish** [comment]
close as ALD contract has the implementation solving this.
