### ISSUE TITLE
Rollout Spec for DEX MVP1 implementation

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#107]
### Note
Parent story: #106 
We need to have a spec first before anything can starts on this.

Quite likely some of the previous work can be reused: https://hackmd.io/ox5XLjdPRK6N3Mp9T9eUZw?view

### Successful Criteria
Has a spec out with details of the followings:
1. Private Deposits
1. Off-chain settlement validation
1. Withdrawals: standard and 2-phase withdraw

Quite likely this would need to define "order" submission and cancelation as well (though they do not need to be implemented).

**Comment by boolafish** [comment]
Hi, @bg1156 we are tracking the issue here: https://github.com/omisego/plasma-contracts/issues/95.

**Comment by bg1156** [comment]
thanks

**Comment by boolafish** [comment]
Doc from @paulperegud : https://hackmd.io/kJu4CdniTGCQbCfl4berOw?view

[Note]
Things to solve: 
1. How do venue provide confirm sig to traders? Trader need that to create withdrawal tx. What do we do to protect venue withholding confirm sig?
    - One issue for trader exit from input is that, venue can hold the challenge to the last minute to reveal. In the case operator mines invalid tx, traders would not have time to react to create new exit with the latest revealed confirm sig.
1. When operator and venue are both hacked, it is possible to have a valid settlement transaction after invalid tx mined by hacked operator. None of our proof would help solving this situation.

[action item]
For the first issue
    - Can we make confirm sig a message tx and must be mined in child chain? And the next transaction must prove confirm sig tx is mined?
    - In the case of solving this by trader exit from input, can we let venue replace instead of cancel with the next settlement tx?

**Comment by paulperegud** [comment]
@boolafish please review. https://hackmd.io/kJu4CdniTGCQbCfl4berOw

**Comment by Nikodemek18** [comment]
@boolafish @paulperegud I understand the document was already reviewed and this is our final version. Right?

**Comment by boolafish** [comment]
Doc here:
https://omisego.atlassian.net/wiki/spaces/RES/pages/56328256/Restricted+custody+MVP1+spec?atlOrigin=eyJpIjoiNDBiNWE5NjBjZmNhNDM2ZTljNDRhZDM5NDlmYzcxNGIiLCJwIjoiYyJ9
