### ISSUE TITLE
Do we want to have bumping version upgradeability?

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#108]
### What is upgrade by version
Upgrade by version means we do smart contract upgrade by deploying a new one, bumping the version on our either proxy contract or registry contract to change the pointer to new version. 

With abstract layer design, it is possible to upgrade by "adding" new stuffs. For instance, new tx type and exit game. Now comes the question, do we want the ability to upgrade by version?

### Why do we not need this
In production, we would probably prefer to limit ourselves to be able to upgrade only by "adding new things" + "exit and join" for security reason. 

One possible way to do this securely enough is to add a limit of all upgrade by version need to wait two weeks (as plasma m(ore)vp security)

### So, if not in prod, when do we need this?
I see potential value of this is to upgrade our pipeline test env using this method. In development, we push several changes and then audit once. Currently, those "several changes" can basically break our development and staging and need to cleanup our env. With upgradeability of abstract layer, though we can add new txs, but that means our watcher/operator codes needs to support such new tx types (**and meanwhile maintain the old tx types**). If we can just bump version, we only need to adjust our operator codes to support the code changes (before the changes go to audit/prod). 

### Side notes
There is two layers for this topic actually, the plasma framework layer that supports the basic feature and the abstracted layer for tx types.
1. Framework Layer: Without upgrade by version, there is no way to upgrade the framework actually. But fairly speaking, this part is more stable and rarely do feature land here.
1. Abstracted Layer: There is a possibility of isolation of predicate can make adding new stuffs out from operator and watcher. However, this is still remain a research topic. Some of our draft idea is [here](https://omisego.atlassian.net/wiki/spaces/RES/pages/47480840/Predicate+Isolation+Idea?atlOrigin=eyJpIjoiNzRiNmNiNmY2NTJjNGIwZGFmMGU4ZjkxMGQ1OTYzN2EiLCJwIjoiYyJ9)

**Comment by boolafish** [comment]
[Note]
On the migration plan meeting, we decide to move forward without this feature first.

**Comment by boolafish** [comment]
Following is what I think our deployment process would be like in the first version of implementation without upgrade by version:

1. Write/Update contracts
1. Deploy the contracts 
1. Register a new tx type with the deployed contracts (I think it is fine to register before elixir code comes in because there is no way to use new type before server code support, unless it is deposit tx)
1. Write/Update the Elixir code needs to either:
   - be able to handle both (existing + new) registered version 
   - disable old tx type support directly, and left trash data in our DB (← I guess this is what we would do in development env)
1. Deploy the elixir code

cc. @InoMurko @jbunce

**Comment by kasima** [comment]
Interesting possibility but I agree that we wouldn't necessarily want to do upgrade by version in production for security and complexity reason.

And if we aren't using this method in production, I would want staging and development to match. Otherwise, we're introducing a significant difference at production, which comes with risks. I'd like to match production as much as is reasonable throughout the development process to give us the most amount of experience with the behavior of the whole system.

**Comment by boolafish** [comment]
Okay, I think we have enough decision for a while. closing this.
