### ISSUE TITLE
Solve SE output and IFE input collision without relying on exit id

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#110]
### Why
Abstract design requires each exit games to be as independent with each others as possible. Current solution for the collision requires the knowledge of "exit id" of input transaction. However, the input transaction's "exit id" would be decided by its own game.  We do not want to be in the situation while designing exit game for new tx we need to take care of all input exit games' logic.

previous discussion: https://github.com/omisego/research/issues/78#issuecomment-492170043

**This is a blocker for abstract layer implementation, we need decision on this**

### Proposal
In non-canonical challenge, an IFE can be challenged by input that is already finalized, and this would have highest priority so that nothing can respond this.

Alternatives, [Kelvin's solution](https://github.com/omisego/plasma-contracts/issues/102#issuecomment-495809967) for #102 might just as well solve this?

### What to do
- [x] Basically, there must have dependency somewhere in MoreVP. Currently it is linked by exit id. We should also analyze is it possible to use `utxo pos` instead of `exit id`?
- [x] Check whether Kelvin's solution for #102 would just as well solve this

**Comment by boolafish** [comment]
For the first point of `exit id` and `utxo pos`:

Okay, I think the problem is more about naming and variable responsibility.
Currently we use `exit id` for two things: 
1. A id to get essential data from `exits` mapping
1. A id to sort of represent output

Also, to check an output is finalized, we re-use the `exits` mapping + the fact that once finalized, the `owner` field would be cleaned up. So an existing `exits` mapping + empty owner indicates finalized output. (relevant code: [here](https://github.com/omisego/plasma-contracts/blob/master/contracts/RootChain.sol#L406))

The main issue for the abstract design is that the id to get essential data should not need to know about how other exit game decides their id for data. The id to represent output for sure would be a global logic.

Since we are having abstracted `vault` (originally named `wallet`), we can have a map there recording finalized outputs (with `utxo_pos` or `output id` as key). We can still check the input is finalized or not on IFE starts.

One thing would be hard to keep is that, current contract [automatically challenges the input SE](https://github.com/omisego/plasma-contracts/blob/master/contracts/RootChain.sol#L412). 

However, I would really like to argue it is more of a best practice to move this out to the responsibility of watcher instead. This simplifies the contract code and safe some gas on IFE starts.

**Comment by boolafish** [comment]
re: Kelvin's solution (checking all inputs on processExit) impact on this:
It would solve this. IFE no longer needs to care about inputs' situation during the game process. The canonicity would be double checked right before finalizing the exit.

Same as previous comment though, watcher needs to challenge existing SE when there is an IFE using the output.

**Comment by paulperegud** [comment]
> Abstract design requires each exit games to be independent with each others. Current solution for the collision requires the knowledge of "exit id" of input transaction. However, the input transaction's "exit id" would be decided by its own game. 

I don't really think that this is a good idea. ExitId can be always equal to utxo_pos or output_id. Full isolation would mean that two games can independently exit the same utxo.

**Comment by boolafish** [comment]
Yes I agree the id for output(utxo pos or output id) is a global thing. Please take a look on my first comment here. In my design, ExitGame and ExitProcessor need a id to get the data out. And that’s it. I think that one don’t need to make sure how other exit games wanna design their id to get data out. 

For id act as the output identifier, with the vault design, I think it only needs to live there.

**Comment by boolafish** [comment]
BTW, the main reason I am pushing back this so hard is that I want the storage of exit games is isolated. It is hard to have a single global exit mapping that allows all exit game contracts to have write access and make sure all new exit game contract won't break existing ones.

As for logic isolation I would like to go as far as possible. If it is just not feasible then....sigh, let's code whatever is needed. Thus, if we do prefer to use exit id as the way to solve collision, then we can let the ExitGameA to call ExitGameB with the essential data to check whether an exit is already started.

However, if Kelvin's solution is the only one we have and need to implement that anyway, I think it just solves the collision mostly already. The only leftover of auto challenging SE sounds like the clear responsibility of watcher to me.

**Comment by boolafish** [comment]
[Note, call with Pepesza]
So `exitId` is a compact way to holds all the needed data (flags). We do need to change current id design a bit because it rely on the fact on how many inputs/outputs in the bit it is using.

However, the above comment of "global storage access" issue is not clear yet how to solve. Also, the requirement of global storage would make predicate not stateless might be an issue too.

**Comment by boolafish** [comment]
So far, it seems like we need to go forward to implement Kelvin's solution. So we can remove the cross check by nature.

I would go forward using vault to keep the finalized outputs if there is no better solution.
