### ISSUE TITLE
MVP/MoreVP switching

### ISSUE THREAD

**Issue by paulperegud** [omisego/plasma-contracts#113]
It would be great if we could abstract away the fact that MVP transactions outputs must be accompanied by confsigs when spend (etc) into something smarter than an if statement.

**Comment by boolafish** [comment]
Nope, there is no need for if statement on `output`. In fact, a same output type can possibly exists in MVP or MoreVP tx type. What decides the protocol would be the `consuming tx`. Thus, If I analyzed it correct in [previous research](https://github.com/omisego/research/issues/83), all it takes is in the predicate. A predicate of `output-->MVP` tx would need to take in confirm sig (which would be part of the data on consuming tx) while `output --> MoreVP` doesn't.

**Comment by boolafish** [comment]
[note to myself]
In the predicate, for the following cases:
MVP (tx1) --> MoreVP (tx2)
1. need confirm sig of tx1

MoreVP (tx1) --> MVP (tx2)
1. need confirm sig of tx2

MVP (tx1) --> MVP (tx2)
1. need confirm sig of tx1. (I think we need this, but from the [MVP repo](https://github.com/omisego/plasma-mvp/blob/c121672d91d2009bcc4f404d7c7027a917e8778b/plasma/root_chain/contracts/RootChain.sol#L224), it is not there. Do we not need this? can you help me double check this @paulperegud )
1. need confirm sig of tx2

---
`witness` might not be part of the transaction. For instance, the confirm sig here is not. The predicate need to not rely on consume tx + input index to get witness (current design, need to change).

**Comment by paulperegud** [comment]
Whenever one is referencing or presening a MVP transaction, confirmation sig must be delivered. The only party that can meaningfully use MVP tx without confsig is operator when he is including new tx into the block.

* If I'm spending MVP output, I need to show confirm sig.
* If I'm exit MVP - I need to show confirm sig.
* If I'm challenging WITH MVP tx, need to show confirm sig.
* When I, as an operator, am including a spend of MVP tx, I need to show it's confsig.
* When I'm exiting a MoreVP tx via in-flight exit I need to show my inputs confirmsigs if they are MVP.

This is why we need to have protocol type ID in signed data - that would allow contract to distinguish if tx needs confsig or not.

**Comment by paulperegud** [comment]
> need confirm sig of tx1. (I think we need this, but from the MVP repo, it is not there. Do we not need this? can you help me double check this @paulperegud )

Challenger presents confsig for challenging tx. Exitor has already presented confsig for tx he is exiting with.

**Comment by boolafish** [comment]
The switch would need to solve the issue of how venue would send confirm sig to traders:
https://github.com/omisego/plasma-contracts/issues/107#issuecomment-498973962

However, more of a research not implement at this moment for that. And with the above statement, I think it is clear in a way. Will remove the blocker tag but keep this open if we need a placeholder for discussion.

**Comment by boolafish** [comment]
closing this as there is issue tracing the remaining problem: https://github.com/omisego/research/issues/100
