### ISSUE TITLE
Mechanical Re-org protect mechanism implementation with abstraction

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#118]
Potentially we can have a predicate for the re-org protection logic/state. So we can even in the future switch our protection mechanism.

doc: https://gist.github.com/paulperegud/3fb4bb96693abe2e0b175f7b20e64362

**Comment by boolafish** [comment]
Moving from slack

---
pepesza [8:06 PM]
@boolafish alternatively this mechanism can be built as follows:
```
    modifier onlyOperatorOrProxy() {
        require(msg.sender == operator || msg.sender == proxy);
        _;
    }

    function submitBlock(bytes32 _blockRoot)
        public
        onlyOperatorOrProxy
    {
    ...
    }
```
pepesza   [19 hours ago]
The proxy contract has it's own storage and does the calculations that check if operator has the same view of the chain as the chain itself.

pepesza   [19 hours ago]
`Proxy` ofc can be called just by `operator`

pepesza   [19 hours ago]
With this construction re-org thing is opt-in from operator.

pepesza   [19 hours ago]
BTW, I'm just writing on how we can leave us some space to add re-org thing later. Not the mechanism of re-org protection.

**Comment by boolafish** [comment]
[idea]
From the pseudo code of the doc, it seems like from the contract side it is rather simple to implement.
Alternative might be just do it and be a separated function first. Audit both function, with the contract first only capable of doing existing submitBlock and at certain point can deprecate and switch to new one.

**Comment by paulperegud** [comment]
Simplification and optimization. The hash of last block used by operator as input (the most recent spent deposit Ethereum block hash) is the one we should track instead of our own hash of the state of deposits. 

Pros: no need to compute any hashes in the contract
Cons: additional heuristic - if Ethereum block `submitBlock` refers to is >256 blocks old and thus unavailable to contract, just skip the check

**Comment by boolafish** [comment]
Just to leave implementation note. So in PR #241 it takes the path of re-setting authority address to be able to switch from original address to the "proxy" one mentioned above.

That is, we can change the address to a smart contract address and then the new smart contract would do the mechanical re-org check.

**Comment by boolafish** [comment]
closing this as we've already implement the abstraction to migrate to mechanism re-org protection: https://github.com/omisego/plasma-contracts/blob/ea36f5ff46ab72ec5c281fa0a3dffe3bcc83178b/plasma_framework/contracts/src/framework/BlockController.sol#L64-L72
