### ISSUE TITLE
Possible bug in RLP assembly code

### ISSUE THREAD

**Issue by jtakalai** [omisego/plasma-contracts#13]
Following line stuck out on a quick browse-through:

https://github.com/omisego/plasma-contracts/blob/848e0399fdc0b059e151922baf95e58b00fe705c/contracts/RLP.sol#L203

It looks like it should be `mstore(dest, mload(src))`

It's inside the following function:
https://github.com/omisego/plasma-contracts/blob/848e0399fdc0b059e151922baf95e58b00fe705c/contracts/RLP.sol#L194-L217

**Comment by paulperegud** [comment]
This code was reworked as a part of dev-morevp. We will pull this branch in pieces, fixing this issue.

**Comment by boolafish** [comment]
closing this as it is pointing to outdated code :)
