### ISSUE TITLE
[abstract] ExitGame contract for Payment TX

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#133]
### Note
Following functions to be implemented, quite likely could be sub-tasked to multiple PRs:

1. startStandardExit
1. startFeeExit
1. startInFlightExit
1. piggybackInFlightExit
1. challengeStandardExit
1. challengeInFlightExitNotCanonical
1. respondToNonCanonicalChallenge
1. challengeInFlightExitInputSpent
1. challengeInFlightExitOutputSpent

### Reference
To see the discussion of tx format:
https://github.com/omisego/research/issues/102

**Comment by Nikodemek18** [comment]
@boolafish what are the next steps on this one? I have seen some subtasks. Meaning you gonna proceed with them one by one?

**Comment by boolafish** [comment]
Yeah, basically

**Comment by Nikodemek18** [comment]
So we close this thread or keep it for general discussions?

**Comment by boolafish** [comment]
hmm... I am used to keep story and subtasks both open to track our WIP limit amounts in board for Kanban spirit. But we are not really using it anyway so there is no benefit of keeping (sigh). Would close this to simplify the board.
