### ISSUE TITLE
[PaymentExitGame] startFeeExit

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#165]

**Comment by boolafish** [comment]
Hi @paulperegud I am curious what design is in your mind on the fee exit since you mentioned fee exit is sort of different from everything else, and we can just have ONE exit for everything since all calculation can be done in ch-ch and watcher and don't need contract verification.

So what's your plan on this? To put this on `PlasmaFramework` or have a ExitGame just for fee exit (IDK, like a special tx type for fee exit and operator can just mine such tx and exit?)

**Comment by Pongch** [comment]
Hey, given that the Watcher even in the current stage does not have the ability to watch fee exit. Could we add this functionality in the later cycle ?

**Comment by boolafish** [comment]
I think this largely depends on how we're going to do the fee. If the above proposal of having a special tx type for fee is the way we'd like to go, then yes.

**Comment by boolafish** [comment]
[NOTE]
@paulperegud has another potential idea of mining a payment tx directly without input, that would be consider as a fee tx. And then operator can just transfer that tx to another normal payment tx and standard exit that. Or, to just do normal plasma tx.

Anyway, I think we are confident that we don't need to put this into the effort within this audit cycle. We got ways to handle fee in the future.

**Comment by pdobacz** [comment]
> mining a payment tx directly without input, that would be consider as a fee tx. And then operator can just transfer that tx to another normal payment tx and standard exit that

nice! One note however, this would require some thinking, if the operator would be to (trustlessly) handle the collected fees in some manner (like give to a `FeeBurner` contract or distribute among stakers).

If the collected fees just go straight to operator's pocket then yeah, this sounds like a least-effort solution :tada:

**Comment by boolafish** [comment]
Ah yeah some other concern that have bumped up during the discussion : the outputId. We probably need some nonce on such fee transaction.

Also, if we ever use empty input as distinguishing deposit tx, it might not work anymore.
