### ISSUE TITLE
Increase the limit of outputIndex

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#168]
In RootChain.sol, output index is using `uint8` so I uses the same size in PlasmaFramework. However, if we are re-using the code, this would limit our DEX batch size to 256 (2^8). I think this is a bit small.

```
    function getOindex(uint256 _utxoPos)
        internal
        pure
        returns (uint8)
    {
        return uint8(_utxoPos % TX_OFFSET);
    }
```

IDK, bump it to uint16 (there is no `uintxx` in between)? However, we have a `TX_OFFSET = 10000` limit here which is smaller than 2^16. Nevertheless, we can check some `MAX_OUTPUT_INDEX_VALUE` anyway. 

Some options in my mind:
1. Bump it to uint16 with some cap/max value limit lower than TX_OFFSET
1. Bump it to uint16 and bump the TX_OFFSET

Any ideas? @paulperegud @pik694 @pgebal @kevsul

**Comment by paulperegud** [comment]
Current TX_OFFSET is big enough for practical purposes. Setting it to 2^16 would be a good move for aesthetic reasons but would also require changes on client side. I think option 1 a better choice.

**Comment by pik694** [comment]
Bumping TX_OFFSET to 2^16 would be good for aestethic reasons (as for programmers and for the computer). In order to make sth human-readable we should use decimal offsets, so probably using `1000` would be a better choice here.

**Comment by boolafish** [comment]
re-open this so we track our implementation of this. remove the question tag.

**Comment by boolafish** [comment]
BTW, I think we can just cap with max value atm: `TX_OFFSET`. 

(at least, might have more) Following lib would be impacted:
- UtxoPosLib
- ExitId (getStandardExitId) only prepared 8 bits for output index now
