### ISSUE TITLE
Deposit fund might be stolen by operator (?)

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#169]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior

Here is the scenario: somebody starts a deposit, however, it gets stuck in memory pool and take a long while to get into a ETH block. Now, operator submits an invalid child-chain block and it get collected into ETH block before such deposit. Now the deposit has lower priority and cannot exit.

## Expected Behavior

The deposit transaction should either fail or promised to be included before any new child chain block?

## Suggested Fix
Add time out to deposit with child chain block number?

## Motivation for Change
Fix bug/issue

**Comment by paulperegud** [comment]
Yeah, this is an old one. This is why exits from deposit have special priority - 1 week. While invalid block's transaction will wait for 2 weeks.

**Comment by paulperegud** [comment]
This is the first time this issue was raised: https://ethresear.ch/t/minimal-viable-plasma/426/14
