### ISSUE TITLE
New deposit verifier of vault should wait certain period to take effect

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#174]
### Why
In this doc: [Upgradeable component and its security analysis](
https://omisego.atlassian.net/wiki/spaces/RES/pages/66125827/Upgradeable+components+and+its+security+analysis)

If I analyzed it correctly, new deposit verifier should wait some time to be able to take effect. (same issue as new vault)

The earliest time for new verifier to be able to take effect should be one min-finalization-period

### Current design
It is using `setDepositVerifier` to directly and immediately swap the verifier to upgrade to new tx type.

### Possible designs
1. Register verifier with version and then when time allows, upgrade to such version.
1. Register verifier with tx type. deposit function take `tx type` as input so it would knows which to use. Before calling verifier, the deposit function would check the min taking effect time.

### Successful critieria
update both `ERC20Vault` and `ETHVault`

**Comment by pnowosie** [comment]
Implementer note about mentioned possible designs.
I took the 1st option, which is 
* when next (second, ...) deposit verifier is set on the Vault, it's registered along with its effectiveness time (now + MIN_EXIT_PERIOD)
* when deposit is made after the effectiveness time new deposit verifier is swapped with currently in-force one.
