### ISSUE TITLE
Use "exitable" timestamp instead of "utxo pos" as priority when enqueue

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#175]
### Why
I somehow was in the wrong impression that priority queue is using utxo pos as the priority. Not until recently I realized (#169) it should be "exitable" timestamp.

### Successful Criteria
- `enqueue` function of `ExitGameController` probably does not need to take `priority` anymore, it can get `exitable` data from `ExitModel.Exit` and use that directly.
- SE for payment already implemented enqueue with utxoPos, should alter that.

**Comment by pdobacz** [comment]
Sorry again for a late comment:

I think utxoPos is needed. 

Contrary to earlier comment on slack it is not only about disambiguation. 

"Exitable" timestamp is going to be equal for txs that were in the same child block (and for txs that were in different child blocks, but mined in same eth blocks). On the opposite, priority should respect the ordering of txs within a block. By using only "exitable" timestamp, you'd level out txs, that should have been ordered in the priority queue the same they were ordered in the blocks. C.f. the snippet from `v0.2` contracts, taken from `getExitableTimestamp`:

```
        uint256 blknum = _utxoPos.getBlknum();
        ...
        return Math.max(blocks[blknum].timestamp + (minExitPeriod * 2), block.timestamp + minExitPeriod);
```

The "exitable" timestamp doesn't contain the ordering of txs in blocks anymore, so you need to re-apply it using `utxoPos`

**Comment by boolafish** [comment]
Thanks for this. I update the PR to take both `exitableAt` + `txPos` to be the priority used in queue.
