### ISSUE TITLE
Operator can steal fund by replaying tx on plasma

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#187]
## Issue Type 
```
[x] bug report
[ ] feature request
```

## Current Behavior
An operator can mined a tx that is the same as an existing tx, and immediately exit with such tx. Since we are relying `exitId` which is derived from the `txHash` to check exit not started yet, the replayed tx would have same `exitId` as an existing one and now the old one would fail to start exit.

## Expected Behavior
The old one should be always possible to exit.

## Suggested Fix
I don't know, do the same thing as deposit as we always put `utxoPos` as part of composition of `exitId`?

**Comment by pdobacz** [comment]
but doesn't exiting from said tx require a signature of the utxo owner? Operator can't just exit from someone else's arbitrary tx.

**Comment by boolafish** [comment]
Ah your right, I’m being idiot
