### ISSUE TITLE
Rename Good and Bad ERC20

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#188]
### Why
PR comment from @pik694 
https://github.com/omisego/plasma-contracts/pull/183/files#r308000861

We can probably name those better as `Good` and `Bad` sounds naive and a bit misdirecting.

### Successful criteria
- Come up with a good naming for the two.
- Refactor all codes including tests.

**Comment by kevsul** [comment]
The name `BadERC20` was taken from the article that described the problem:
https://medium.com/coinmonks/missing-return-value-bug-at-least-130-tokens-affected-d67bf08521ca

I agree that it's ambiguous, how about changing it to `NonCompliantERC20` and `CompliantERC20`?
Ideally we wouldn't need `CompliantERC20` - it's only there to force compilation of the `ERC20Mintable` contract to be able to use it in the tests. There may be a better way around this.
