### ISSUE TITLE
Start Inflight Exit should be input tx type agnostic 

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#205]
### What
In start IFE PR: https://github.com/omisego/plasma-contracts/pull/196, it directly uses `PaymentTransaction` as input transaction. We would like to not hardcode input tx in the `PaymentInflightExitable`.

### Why
We want to be able to **not** audit again the main code when we are adding DEX feature or extend to any other tx that can be input of `Payment transaction`.

### Proposal solution
We could probably have a `verifyStateTransition` predicate for IFE. This would basically check given input txs and the tx with the proof/witness, the state transition in such transaction is valid.

We would swap the predicate when we are changing/adding new input txs. Dependency tx types can be hardcoded there.

### Successful Critieria
- The `PaymentInflightExitable` should not hardcode `PaymentOuput` as input. (one example [here](https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/exits/payment/PaymentInFlightExitable.sol#L243), should be more in current code base)
- In `PaymentExitDataModel`, `inputs` of `InflightExit` should not be `PaymentOutput`: [code here](https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/exits/payment/PaymentExitDataModel.sol#L34). (I guess need to be sth like `bytes`, or if there is better idea?)

**Comment by boolafish** [comment]
[side note]
I have a feeling this verifier would need to return the `youngestUtxo` (potentially more?). Something similar to our ERC20 deposit verifier: https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/vaults/verifiers/Erc20DepositVerifier.sol#L14

**Comment by boolafish** [comment]
> In PaymentExitDataModel, inputs of InflightExit should not be PaymentOutput

When I was writing `piggybackInFlightExit`, I have this idea of using another struct that is defined in this InFlightExit file. So this new struct would become our interface that all input tx need to be able to provide data to:

```
   struct WithdrawData {
        address payable exitTarget;
        address token;
        uint256 amount;
    }

    struct InFlightExit {
        uint256 exitStartTimestamp;
        uint256 exitMap;
        uint256 position;
        WithdrawData[MAX_INPUT_NUM] inputs;
        WithdrawData[MAX_OUTPUT_NUM] outputs;
        address payable bondOwner;
        uint256 oldestCompetitorPosition;
    }
```

my wip piggyback branch code: https://git.io/fjQAN

**Comment by pgebal** [comment]
> [side note]
> I have a feeling this verifier would need to return the `youngestUtxo` (potentially more?). Some construction similar to our ERC20 deposit verifier: [code](https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/vaults/verifiers/Erc20DepositVerifier.sol#L14)

@boolafish It looks hard to work around not providing input utxos positions when starting IFE. As we have those utxoposes, we can find the youngest just by comparing between them, so no need to return them from verifier.

**Comment by pgebal** [comment]
How much do we want to abstract from wire transaction format? 
If we want to take that far, we should probably provide uint256[] inputTxsTypes as another argument to start in-flight exit.
Based on those input tx types, a concrete StateTransitionVerifier (predicate to implement in this issue) could query another abstraction (let's say Transaction interface) about transaction's inputs / outputs. Tomorrow I should have some pseudo-code to illustrates that, I will keep you updated @boolafish.

**Comment by boolafish** [comment]
> so no need to return them from verifier.

Ah...you're right on this. And in fact, youngest position has nothing to do with the state transition verification anyway.

> a concrete StateTransitionVerifier (predicate to implement in this issue) could query another abstraction (let's say ITransaction interface, in fact it's implementations for concrete tx types) about transaction's inputs / outputs to get what it needs to verify that transition is correct (no overspending, etc.).

Looking at the description I am confused actually. Then how is the `StateTransitionVerifier` different with `ITransaction` ? Seems like doing the same verification? 

Yeah, if you got anything to show the concept please let me know. Or even just the interface that you're aiming to do would be good.
