### ISSUE TITLE
bug: challenged exits can be processed by finalizeExit

### ISSUE THREAD

**Issue by paulperegud** [omisego/plasma-contracts#21]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
`finalizeExits` will send money from challenged exit to 0x0.

## Expected Behavior
Successfully challenged exits should not lead to any money movements.

## Suggested Fix A

Add a check in finalizeExits loop which will make sure that if `owner == 0`, than no money is being moved.

Pro: trivial implementation; `challengeExit` stays cheap
Con: challenged exits stay in the queue, bloating it, increasing gas needed to operate on queue

## Suggested Fix B

Alternatively, we can remove exit from the queue on successful `challengeExit`.

Pro: decreases size of the queue early, preserving everyone's gas
Con: `challengeExit` gas cost is no longer constant; needs careful implementation of random access remove for `PriorityQueue` structure.

**Comment by paulperegud** [comment]
Fixed in #19, Suggested Fix A is implemented.

**Comment by kfichter** [comment]
Yeah I don't know that it's possible to implement B without a very complex data structure.

**Comment by paulperegud** [comment]
Fix merged, closing.
