### ISSUE TITLE
A more generalized SpendingCondition Registry

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#214]
### Why
At the time a developing Standard Exit, `PaymentSpendingConditionRegistry` was introduced to cover the spending condition concept (or the output predicate). However, in SE, it only cares about the outputting case `PaymentOutput -> Some tx` and does not take input into consideration: `Some Tx -> Payment Tx`.

When start IFE PR is out, I sensed that the original design is not really designed for the input scenario. The registry naming and the interface might not be generalized enough if we want to re-use that for a more global use.

### Proposal interface of registry
```
function verify(
    bytes inputTx,
    uint16 outputIndex,
    uint256 inputTxPos,
    bytes spendingTx,
    uin16 inputIndex,
    bytes witness,
    bytes optionalArgs,
) external view returns (bool);
```
With `inputTx` + `outputIndex`, one should be able to get the `output` data. Why passing in `inputTx` instead of `output` though? In the exit game, it is more common that the function would accept encoded tx instead of encoded output. As a result, if we are passing in encoded output, we would need to re-encode in our exit game function somewhere.

Also, with `inputTx` + `inputTxPos` + `outputIndex`, we can build both `utxoPos` and `outputId` depends on our need. However, `inputTxPos` must be proven correct somewhere outside the spending condition.

Optional args is there to cover things that is to be customized:
1. output guard pre-image might be a good fit there.
1. in the case of DEX settlement, where inputs/outputs of tx might just be a merkle root when decoded, we need to pass in the original output data + merkle proof and not get those from decoded tx.
We can pass in an `abi.encoded(customStruct)` and in our contract.

### Proposed Functionality of the registry
Instead of using the origin `(outputType, spendingTxType)` pair, we would like to add another `inputTxType` to isolate the registration process. Biggest reason is that we want to `Freeze` the registry of an input tx type to accept new spending txs. That is, we first register spending conditions of a input tx type, and then we would freeze future registration on such tx type. We only deploy our exit game contract after such tx type is frozen so user knows how the tx can be spent and know it would not be changed.

Also, this means now (`inputTxType`, `outputType`) should become the unique type identifier of an output. Same `outputType` in different `inputTxType` can mean different things now.

Some basic functionalities of the registry:

```
register(inputTxType, outputType, spendingTxType, spendingConditionContract);
freezeInputTxType(inputTxType);
```

### Where to put this Registry?
I'd like to propose to make this registry a standalone contract itself, instead of putting this into `PlasmaFramework`. Reason for this is that if we ever found out current interface is not flexible to our use case, we can always still develop new exit game contracts taking new interfaces without off-boarding whole plasma framework.

As a result, different exit games can share this registry as much as the abstraction holds while when abstraction breaks there is still way to move on.

### Side note
For registry using `outputType`, it should change to be using `(TxType, outputType)` as the identifier, since `outputType` is no longer globally unique. It is only unique under a certain tx type.

For example, the `outputGuardRegistry` would need to get the outputGuardParser using (tx type, output type) pair instead of current implementation of using output type only. Also, it should freeze the tx type before registering the exit game to framework.

**Comment by boolafish** [comment]
### Problem of the above proposal
So there is a problem if we only rely on the `freezeInputTxType`. This solves [current tx -> another tx]. However, it still opens a hole to [some invalid new tx -> current tx]. That is, operator can adds a new spending condition using new tx type, of break the check on IFE.

### New proposal
We have a global registry + each exit game whitelist its potential input/output tx type.
This makes the mechanism much easier. Exit game would check if such tx type is in its own whitelist first and then get the contract from the global registry. We don't care if there is any bad contract on the registry as long as those whitelisted in ExitGame is valid. Now ExitGame is safeguarded by the quarantined period we already introduced.

**Comment by pdobacz** [comment]
some comments:

> ## Proposal interface of registry

I think "of spending condition" was meant

> Same outputType in different inputTxType can mean different things now.

This seems strange, what is an example of such case? (in `elixir-omg` I have tentatively tried having only `outputType` drive the spending condition and `inputTxType` drive the `outputType`. I'd be ideal for `outputType` to be enough to determine the spending condition, without having to "backtrack" to `inputTxType`

> Where to put this Registry?

by the property that `ExitGame` drives upgrades, one can also just bake in this registry into an `ExitGame` instance deployed and not worry about the `freeze` part at all. Expandable `ExitGames` (with new spending conditions to be added) can be upgraded to later, if needed. Let's keep it simple

**Comment by pdobacz** [comment]
ah clicked "Comment" to early

>     `uint256 inputTxPos,` (in the spending condition API)

Consider moving this to optional args, since some spending conditions won't care about inclusion, or so it seems at least :thinking:

**Comment by boolafish** [comment]
>  one can also just bake in this registry into an ExitGame instance deployed and not worry about the freeze part at all

Does this means instead of a global single registry, for each exit game we put a registry (that already has all the stuff needed registered) and make sure such registry cannot further register? So we just inject different registries when deploying exit game?

> Same outputType in different inputTxType can mean different things now.

The thing that bothers me is output type 0. It is currently used in Payment Tx (v1) as Payment output. Now, when Payment tx v2 comes, the exact same output can be spent in different spending tx types now. hmmm, in elixir how do you verify the difference when the tx is in different version like the example above without specifying input tx type?

> Consider moving this to optional args

hmmm, I forgot the reason why I move it out lol. I remember at first I put it in optional (in another doc) and then move it out when I write this issue. I will try to find out the reason and come back to this.

**Comment by boolafish** [comment]
ah, no I recall why I put `txPos` out from optional, it is because though normally `outputId` can be build without utxoPos, but in the case of deposit tx as the tx bytes can collide, we currently use utxoPos as the extra nonce (I don't like this, but I cannot find an easier way at this moment if not breaking how deposit tx is constructed). As a result, it seems like we do need ways to build `utxoPos` even `outputId` is all we need.

**Comment by boolafish** [comment]
[note from call with @pdobacz ]

1. Piotr proposes `outputType` -> `spendingCondition` relationship. 
1. Piotr imagines a system with all current state as output, and each output has its way of transition to next output by transaction, as a result one output type with one spending condition should be enough.
1. I mentioned that there are potential use cases that a single output type can be consumed in two type to tx.
1. In such case, it might be hard to decode the spending tx without knowing the `type` of a spending tx. --> A solution to this is to assume tx type would be first field when rlpEncoded, we decode the first field first and then see how to decode the remaining.
1. Back to the high level abstraction of outputs in a system, what I see is that the "SpendingCondition" of what Piotr is proposing is a "`Or`" statement of what I am proposing. That is `SpendingCondition_of_Piotr_proposed = spendingCondition1 or spendingCondition2 or spendingCondition3....`. Those spendingCondition1, 2, ... are on the gratuity of using pair `(outputType, spendingTxType)`

**Comment by pdobacz** [comment]
:joy: You beat me to putting a comment here after our call :).

Ad 1-5. I see your concerns, let me propose that we have 2 registries with entirely different behaviors (in light of the security vs API segregation):
  - SpendingConditionRegistry - it is fixed for an `ExitGame`. It maps `output_type`=>`SpendingConditionImplementation` and defines code that is run, when **any** tx attempts to spend a given `output_type`. If an `ExitGame2` is introduced, it must contain this mapping for every output_type its transaction type can create, and it may point to an old `SpendingConditionImplementation`. This registry is **security** oriented, i.e. it defines how to exit from effects of new tx types introduced), auditors must audit this
  - TransactionTypeRegistry - it is defined on the `PlasmaFramework` level and serves merely for dispatching. It maps `tx_type`=>`ITransaction`'s implementation, that has functions like `decode`, `get_inputs`, `get_witnesses`, which need to be implemented for every tx type. This registry is **API** oriented and unprotected (sic!) - adding stuff to it doesn't need to be audited, until there's no `ExitGame` that leverages this transaction type. 

This way, existing outputs know when they can be spent via the "old code" - the spending conditions that can only be introduced via `ExitGame`. Those spending conditions speak to the abstract `ITransaction` interface of the spending tx to get the stuff they need. They do it _agnostic_ of the spending tx type implementation.

I've got a rough sketch of the flow here, lemme draw a nicer version of it and post :)

**Comment by pdobacz** [comment]
![20190823114331416_0001](https://user-images.githubusercontent.com/5735525/63585637-e4c37f00-c59f-11e9-8f50-88a13f371d86.jpg)

ugh, I hope it makes sense, sorry for the terrible handwriting...

**Comment by boolafish** [comment]
Some problem I found in the comment:

> ITransaction's implementation, that has functions like decode, get_inputs, get_witnesses

1. witness should be injected in as witness is not really part of rlp tx data. But it's fine, just inject it and solve this.
1. `decode` interface would not work, you'd need to specify which `struct` your are returning in such decode interface and then you become non tx type agnostic. However, decode (at least on output level) is necessary (IMO) because it is quite possible that there is a spending condition, for example, want to check the token and amount of a ERC20 token output. (imagine you'd like to check DEX order amount vs output amount for example). I think in practice to be able to decode in last minute you will still need logic like:
```
if spending tx type is 1:
    verify1(rlpTxBytes, .....)
if spending tx type is 2:
    verify2(rlpTxBytes, .....)
```
and each `verifyXXX()` would decode the tx inside. And this is back to the original spending condition design.

**Comment by pdobacz** [comment]
> 1. witness should be injected in as witness is not really part of rlp tx data. But it's fine, just inject it and solve this.

ah yes, absolutely agreed, that was a mental shortcut on my part.

> 2. decode interface would not work, you'd need to specify which struct your are returning in such decode interface and then you become non tx type agnostic.

Ah, good point. Then you could use sth like `decode_and_get_inputs(tx3)`... there's some complications around that, but that would solve the issue :thinking: ?

> 2. "the if part"

I think not - you'd check this outside of `SpendingCondition.verify` - in the `ExitGame.some_action` implementation - there you say you require e.g. some challenge to check validity of the spending tx.

So then the output has been unlocked for spending, but the challenge still will not work, b/c the challenging tx has some flaw.

`SpendingCondition.verify` provides a necessary condition but there might be more conditions which are external.

(ugh I'm fried for today, we'll keep picking at it, I'm slowly getting my head wrapped around this. Thanks a lot for all your help, this is enormously helpful)

**Comment by boolafish** [comment]
One more counter example:
A dex deposit output type can be spent in:
1. Dex settlement:
   - checks venue address signed the tx
   - checks the order is singed by the trader
1. Dex withdrawal:
   - checks the trader signed the tx.

To cover `checks XXX signed the tx`, we can add like an interface like `decode_and_get_authenticator`. However, how are we going to handle the part "checks the order is signed by trader" ? This is a `if dex settlement tx, check the order` logic. And this is not something in general (like signing a tx). Also, we cannot check this in transaction level because we want to make sure whatever tx challenges a SE, it need to provide an order signed by the trader. (That is it has two kinds of lock on the output). 

My understanding of your approach is that, in able to be tx type agnostic, we try to list down our procedure of checks in spending condition, and for each procedure, use interface to get the essential data. Which is the assumption is on we have a standard procedure to follow and we put interface for that procedure. The downside of this approach is that whenever new procedure is needed or designed, we would need new interface to get such data. (And there are like some potential other design to unlock an output, eg. if you know a secret number that is hashed in output, you can spend it. And now, you will need one more interface like `get_secret_number`).

**Comment by boolafish** [comment]
I still think it makes sense to use pair of types to represent here. Following represents what is usually in my mind:

```
output type 1 ------- tx type 1 ---> output type 1
               |
               |-------tx type 2 ---> output type 2
```

So different tx types would represent different path of consuming an output. And in practice, their logic can be pretty different. Of course, you can put your "lock" in the early front which includes all spending tx types, but that's like an `Or` statement to the smaller locks for each types.

So far, `(outputType, spendingTxType)` is still some pairing that feels to me it is pretty making sense in high level abstraction wise or low level implementation wise. This is on the assumption that each spending tx type can only have one condition on spending one output type. As a result, there is one "lock" on each (outputType, spendingTxType) pair.

Back to the original post description where it describes to add another `inputTxType` to the pair. What that essentially does is to add the information of what are the allowed path of an tx type. An example would be `PaymentOutput` in `PaymentTxV1` would only have 2 spending tx types (`PaymentTxV2` + `PaymentTxV2`), but in `PaymentTxV2` would probably have 3 spending tx types (plus `DexSettlement`). Without the `inputTxType` information, we cannot represent such difference.

By adding that, it would be building the **global input-tx-output type path**. So you'll got a graph that would represent the whole existing system that how can an output in a tx being used and what can be an input of a tx. With that, it helps identify usable path from inputs in IFE.

In practice, such a global graph contract would have problem as mentioned earlier comment: https://github.com/omisego/plasma-contracts/issues/214#issuecomment-523722519 due to contract immutability-security. Also, each exit game only needs partial view of the graph (types for inputs, types for outputs and what are possible output types of such tx). 

Now I give another thinking, I think the easiest and simplest way to do all the thing is just have a spending condition registry with `(input tx type, output type, spending tx type)` that is frozen-able. So we register the required paths for an tx/exit game and then freeze the contract. Each Exit Game would just re-register essential paths that it needs. This further removes the need of extra whitelist since whole registry would be frozen.

**Comment by boolafish** [comment]
@pdobacz some more counter examples

1. For input tx type:
`PaymentTxV1` would only accepts input tx type of `PaymentTxV1`. If you don't check input tx type , it would pass the predicate testing if you feed a `PaymentTxV2` type with `PaymentOutput` as input.

2. For spending tx type:
`PaymentTxV1` can only be spent in `PaymentTxV1` and `PaymentTxV2` but not `PaymentTxV3`. If you are spending tx type agnostic, `PaymentTxV3` would pass your testing.

**Comment by pdobacz** [comment]
> One more counter example:
> A dex deposit output type can be spent in:
> 
>  1. Dex settlement:
>     * checks venue address signed the tx
>  2. Dex withdrawal:
>     * checks the trader signed the tx.

I see this now, this is a very good find! Oh man, and I felt so close to knowing my way around this. Let's see again: (BTW the speccing out of the DEX helped me a lot here!)

In light of your remark it seems, the gist of the problem here is that we have
 - same output
 - same-ish witnesses (part is same (preimage) part is different (sig))
 - different semantics (someone else's sig must be present)

The solution could be what you propose (however, I think conceptually, this could end up being just a concealed version of the `if` you dislike so much - you list out all the possible combinations and their semantics).

What if instead we should refine the concept of the witness? So (adopting "my approach" - `output_type` only selects the SpendingCondition) what if our exemplary Deposit output type can be unlocked _in either of_ those ways:
  - witness supplied is `{preimage, sig, "trader's witness marker"}` - SpendingCondition checks whether the sig corresponds to the trader field in the preimage
  - witness supplied is `{preimage, sig, "venue's witness marker"}` - SpendingCondition checks whether the sig corresponds to the venue field in the preimage. Now in this branch _we expect the spending tx to be a settlement tx_, so we call a specific implementation that essentially checks if the tx contains the required order: `SettlementTx.decode_and_check_if_contains_valid_order(spending_tx)`.

There's one more thought: maybe the missing concept here is to distinguish "closed loop tx/outputs" and "open loop tx/outputs":
 - closed loop are ones like deposits/settlements/withdrawals - they have "fixed" semantics of spending, an output expects a particular spending tx
 - open loop are ones like Payment tx - they only care about some witness being there and are always good

The "open loop ones" are where the protocols "intersect". So you'll use a payment tx output to "enter a closed loop" and you'll get out of this loop by receiving a payment tx output.

Hm, I'm not sure whether this makes sense, apologies about getting philosophical here :). I'd love to hash out the DEX MVP to get full insight on what semantics we're actually modelling, and work from there, very concretely - see what's the simplest thing that captures the notions required and see if it promises some extensibility.

...

> let's sync up on a call some day when you got time.

I worked weird hours today, and might become available late-ish tmr, but yeah, let's do that as soon as possible!

**Comment by boolafish** [comment]
> I think conceptually, this could end up being just a concealed version of the if you dislike so much - you list out all the possible combinations and their semantics

I think such "if" or the branching logic is the nature of the different spending tx would have different ways to unlock an output. What I don't like is to code such "if" because it means some tighter coupling of logics in modules, as a result I tried to loosen it by the interface and with registry depends on type to remove the `if`. 

> witness supplied is {preimage, sig, "trader's witness marker"}

If you're branching with witness, it can be gamed. I can submit a false marker to let the contract think I should use trader's witness marker on a DEX settlement tx. Unless, we are checking the integrity of such witness to be together with the spending tx, and then, we would need to know how to check such integrity then we are probably need tx type to know such knowledge.

Meanwhile, I don't see making branching depends on witness marker would be better than branching by spending tx type though. Also, `SettlementTx.decode_and_check_if_contains_valid_order` requires you introduce some other interfaces which is depends on type?

> open loop are ones like Payment tx - they only care about some witness being there and are always good

I doubt though. Like my counter example above: "PaymentTxV1 can only be spent in PaymentTxV1 and PaymentTxV2 but not PaymentTxV3.". Unless we are making such `PaymentTx` opens to all new Payment tx versions. However, I think making such path open is easier to open to some security concern. This would need to think it over carefully whether it is doable or not.

**Comment by pdobacz** [comment]
> Also, `SettlementTx.decode_and_check_if_contains_valid_order` requires you introduce some other interfaces which is depends on type?

Ah no, my thought was that this is called from within the specific `SpendingCondition` for the deposit output type, so you already have the tx type fixed. This `decode_and_check_if_contains_valid_order` is only present in `SettlementTx` and not in the `ITransaction`. Being within this "closed loop" enables that, as we don't ever anticipate this particular output type to be spent differently.

But I might be missing sth big time here. Let's revisit later.

**Comment by boolafish** [comment]
Sorry for hand writing picture, this is the image on my mind when I am thinking about the global input-tx-output type path.

In the graph, each tx has its own type as well as output. And there are "paths" (p1, p2, ...) that can move a state from one type to another. To represent such path, it seems to me (inputTxType, outputType, spendingTxType) are needed.

To me, it seems like each path could have its own definition of spending condition.

![type_path_graph](https://user-images.githubusercontent.com/6198848/63907171-65c5bf00-ca55-11e9-9a7f-056e4f8b840b.jpg)

**Comment by pdobacz** [comment]
Yeah, I think I hear you, this is very helpful.

1. In this approach, "how much" is SpendingTxType2 defined, at the time when the Registry is the "upper one" i.e. it doesn't yet involve the future protocol?

Is it designed to be a clone of SpendingTxType1 (and then SpendingTxType5 is too), which only difference is that it only creates OutputType2, which is what the "future protocol" is based upon?

2. Sorry to mull this over again, but this time I don't see why InputTxType needs to be here. If OutputType always determines that (I think it does :thinking:), seems safe to drop it and dispatch only on the `(outputType, spendingType)`. Could you please draw up a similar drawing and an example where inputTxType would matter?

3. In general, this is kinda like the open-loop/closed-loop thing, no? you just provide an explicit upgrading tx that transfers one's money from one closed-loop to the next. Am I parsing this correctly?

**Comment by boolafish** [comment]
> 1/ In this approach, "how much" is SpendingTxType2 defined, at the time when the Registry is the "upper one" i.e. it doesn't yet involve the future protocol?
Is it designed to be a clone of SpendingTxType1 (and then SpendingTxType5 is too), which only difference is that it only creates OutputType2, which is what the "future protocol" is based upon?

Yes, it's a clone. We need to predefine the tx structure, the tx type, and also the spending condition.
ExitGame of it is left undefined. I think we don't need to define what output type can that transaction provide as well.

> 2/ Sorry to mull this over again, but this time I don't see why InputTxType needs to be here. If OutputType always determines that (I think it does 🤔), seems safe to drop it and dispatch only on the (outputType, spendingType). Could you please draw up a similar drawing and an example where inputTxType would matter?

Oh....now I see my graph again, and found out I use outputType 2 in PaymentTxV2. Previously, I usually think that we would reuse the outputType for same feature set. So, for example, PaymentOutput is always being outputType, say like, 1 in all PaymentTxV1, PaymentTxV2, and PaymentTxV3.

But yeah, if we limit ourselves to NOT re-use the output type in each transaction type, that is all transaction type creates **new** output type then yeah! This sounds good to me and probably that was the mis-communication between us. So we can drop the `inputTxType` by assuming each `outputType` is unique under different `txType`.

> 3/ In general, this is kinda like the open-loop/closed-loop thing, no? you just provide an explicit upgrading tx that transfers one's money from one closed-loop to the next. Am I parsing this correctly?

I think yes. Just the graph might potentially be more complex when, for instance, we have non-fungible token. It seems to me that the non-fungible token itself might have some loop there as well if there are some fancy feature to-be-developed.

**Comment by pdobacz** [comment]
okay awesome!

Just let me reiterate this once more, to be sure I'm 100% on the same page.

Let's assume it's `(outputType, spendingTxType)` that drives the spending condition, according to you last comment (I too think this makes sense now!).

So the flow is like that: We first deploy the full semantics of PaymentTxV1 - how can it's outputs can be exited from, how it can be presented to challenge those exits.

At the same time (before upgrade) we also deploy partial semantics of PaymentTxV2 - just enough to  be able to challenge PaymentTxV1 exits with PaymentTxV2 instances. We however **do not** let people to exit from the outputs of PaymentTxV2, this is just "not there", because as you said, there's no ExitGame2.

A tricky part is the spending condition whitelist in the ExitGame1. As I understand it says more or less like: "even if there is a weird transaction type PaymentTxV3 presented, and it attempts to spend one of the outputs that are - for instance - standard exiting from PaymentTxV1, it is **not** a valid challenge (even if witness is presented identically as with PaymentTxV1)". The rationale here is that since there's no ExitGame3, no one can leverage this broken PaymentTxV3 so no one is concerned about it attempting to spend from PaymentTxV1. Is this correct?

Probably, being an honest child chain operator, we'd also prohibit the execution of PaymentTxV2 on the child chain.

Now, should the upgrade come we deploy the missing stuff of PaymentTxV2 - so now people can exit from it (ExitGame2). Atomically we introduce a bunch of other transaction/output types that leverage the "not-previously-fully-defined" output type 2, which will "enter the system" as soon as the child chain allow PaymentTxV2 in.

.

I'm now trying to visualize how this plays with upgrades like:
 - introducing DEX (covered)
 - introducing `output_id` input pointer type
 - introducing ERC721
 - fixing a bug in the ExitGame contract

**Comment by boolafish** [comment]
(The following would be more on implementation thought and note and not following the above discussion thread)

So the `optionalArgs` stills bothers me. Though it seems like magically the interface would be super flexible but it is indeed not. Because the what data would be feed in what format is still decided in ExitGame itself. Each implementation still needs to know what are the **real fields** under such `optionalArgs`, and each exit game would differ on that.

Since what data to feed into the optionalArgs is decided on each ExitGame contract (when calling startIFE or challenge), I feel probably what is better is that each ExitGame has the interface it needs.

We (might) need two interface for each ExitGame for a tx type:
1. Output of the Tx of ExitGame --> Spending Tx (out-going direction from the tx of exit game)
1. Input from other tx types --> Spending tx as the ExitGame tx (in-coming direction to the tx of exit game)

So the registry would be more or less like this:
```
direction = OUT_GOING | IN_COMING
register(outputType, spendingTxType, direction, addressOfContract)
```

And as each exit game would know its own interface on each direction, they would just use their own interface to feed data to spending condition contracts. And each implementation is clear on what interface it is relying on.

So if we look back to the "path" concept as above, it would be that for each path, there would be a interface describing the out going direction and another interface describing the incoming direction. However, all out-going direction path of one tx type would have same interface, and all in-coming direction path of one tx type would have same interface.
