### ISSUE TITLE
Current truffle migration would fail for infura

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#218]
@jbunce was not able to deploy contract to rinkeyby.

Some already found issue:
1. in `truffle-config.js`, it is too strict on constructing infura path. As a result, an extra `/` on the end of `INFURA_URL` would fail the deployment. What's worse, truffle silent it and make it hard to find the issue. (It stops after compile the contract without any error/warning message)
1. in `1_check_authority_address.js`, [this line](https://github.com/omisego/plasma-contracts/blob/master/migrations/1_check_authority_address.js#L7) of `eth.getTransactionCount` should add an `await`.

**Comment by kendricktan** [comment]
https://github.com/omisego/plasma-contracts/pull/220
