### ISSUE TITLE
Expand RLP.sol tests using the Ethereum common test cases

### ISSUE THREAD

**Issue by pdobacz** [omisego/plasma-contracts#221]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Suggested Fix

Let's expand the plasma-contracts test suite with tests that use the https://github.com/ethereum/tests/tree/04940788157c88c75b014e5e6969a249f49db4c0 (or more current version?) similar to what ex_rlp does.

See discussion in https://github.com/omisego/elixir-omg/issues/901 for details/background

## Motivation for Change

https://github.com/omisego/elixir-omg/issues/901 & the parent https://github.com/omisego/elixir-omg/issues/853

**Comment by boolafish** [comment]
close as PR https://github.com/omisego/plasma-contracts/pull/339 has ported the tests from Ethereum RLP spec already.
