### ISSUE TITLE
Separation of operator address

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#233]
### Why
We rely on the authentication address (operator address) to be fresh for re-org protection.
https://github.com/omisego/elixir-omg#managing-the-operator-address

However, we need to limit to an address for register new contracts. This seems to conflict with the nonce mechanism of tracking submitBlock only as the registration would break the assumption.

### Current Implementation
Operator address is set on deployment now. This must be change to respect the nonce mechanism. However, this would not be enough for the registry.

# Solution description

## Terminology
- __Operator__ - organization, not an Ethereum address which holds other addresses
- __Authority__ - Ethereum address used exclusively to submit plasma blocks, requires `nonce = 0` as noted below.
- __Deployer__ - Ethereum address used to deploy Plasma framework for the first time
- __Maintainer__ - Ethereum address (can be the same as deployer or Multisig contract) that is allowed to register upgrades (tx types, output types, vaults, exit games, ...)

## Deployment process

Authority address sends __its very first__ transaction that calls `BlockController.initAuthority()` function. This function sets a caller address as Authority address in `BlockController` which allows for block submission and sets a Authority address nonce - so the Plasma blocks numbers will correspond to the address nonces (`1000 * nonce = blknum`).

## Changing an Authority address
To allow #118 it's possible to replace `authority` address by calling `BlockController.setAuthority(address)` from the `maintainer`. 

## Deployer - maintainer separation
Further separation of `deployer - maintainer` is continued in #242

**Comment by pdobacz** [comment]
> Introduce a separate address for upgrade/register?

I'm all for it, also for other reasons than those you've listed:

It sounds like good practice to separate the "hot privkey" for `submitBlock` from the `"cooler" privkey` used for upgrades.

We're looking into introducing a multitude of keys anyway: `feeExit` requires a separate operator-owned address (or a contract, if we decide to go down the `FeeBurner` path). I imagine there might be more cases of that.

Also the upgrade/register address might make sense to be a multisig.

**Comment by pnowosie** [comment]
After short internal chat we've decided on solution which might be future proof.

# Solution description

## Terminology
- __Operator__ - organization, not an Ethereum address which holds other addresses
- __Authority__ - Ethereum address use exclusively to submit plasma blocks
- __Deployer__ - Ethereum address used to deploy Plasma framework for the first time
- __Mainteiner__ - Ethereum address (can be the same as deployer or Multisig contract) that is allowed to register upgrades (tx types, output types, vaults, exit games, ...)

## Deployment process
Plasma Framework constructor accepts Maintainer address as a parameter. During deployment 
Deployer address sets Maintainer address. It could be the same address as Deployer for test networks or dedicated Deployer address (possibly multisig) responsible for registering components.

Note that __Authority address is unset yet__.

Maintainer address register appropriate components (sets addresses of component contracts to the registries). Component contracts can be deployed by deployer or maintainer it does not matter, but only maintainer can run `register...` functions on framework.

Authority address send transaction that calls `BlockController.init()` function. This function sets a caller address as Authority address in `BlockController` which allows for block submission and sets a Authority address nonce - so the Plasma blocks numbers will correspond to the address nonces.

**Comment by pdobacz** [comment]
LGTM, just:

> or dedicated Deployer address (possibly multisig) responsible for registering components.

"or dedicated **Maintainer** address" or "or dedicated address"

**Comment by jbunce** [comment]
Typo: Mainteiner

**Comment by boolafish** [comment]
A minor feature request, can we make the authentication address transferable? 

The following issue proposed a proxy address which I think we can instead of checking is authentication address or proxy address, we just transfer the ownership to the proxy address.
https://github.com/omisego/plasma-contracts/issues/118

**Comment by pnowosie** [comment]
> The following issue (#118) proposed a proxy address which I think we can instead of checking is authentication address or proxy address, we just transfer the ownership to the proxy address.

@boolafish - if I got your comment - from this task perspective we would need another function that allows us to replace the authority address (aka block publisher address) in the BlockController.

I could be smth like:
```lang=solidity
function setAuthority(address newAuthority) external onlyOperator { 
  authority = newAuthority; 
}
```

**Comment by boolafish** [comment]
Yeah, that’s the functionality  in my mind. Also some possibily same logic code:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/ownership/Ownable.sol#L64
