### ISSUE TITLE
Use solhint for linting Solidity code 

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#240]
## Description 
Currently there are no conformity checks for Solidity code enforced. We should agree on style rules and enforce them throughout the project. 

## Remediation 
Let's use solhint and I propose the the following configuration for it:

```
{
  "extends": "solhint:recommended",
  "rules": {
    "indent": ["error", 4],
    "bracket-align": "off",
    "reason-string": ["warn",{"maxLength":128}],
    "separate-by-one-line-in-contract": "warn",
    "no-empty-blocks": "off",
    "compiler-fixed": "off",
    "not-rely-on-time": "off",
    "mark-callable-contracts": "off",
    "compiler-version": ["error", "^0.5.0"]
  }
}
```

It should be straight forward to fix most of the issues. For cases where use of assembly is absolutely necessary, I would suggest to add a comment that gives a reason why it is required and another line that indicates to solhint that it should not emit warnings in this case. Example -> https://github.com/OpenZeppelin/openzeppelin-contracts/blob/e855ca450a1f55202e5461a6a7ba7038a32eca3c/contracts/cryptography/ECDSA.sol#L39-L41

Once we have cleaned up the code we can add a CI job that checks that there are no warnings left. 

```
solhint --max-warnings 0 "contracts/**/*.sol"
```

**Comment by boolafish** [comment]
I am guessing it would argue for using `pragma experimental ABIEncoderV2;` as well, can we turn that off? (if it will argue about that)

**Comment by thec00n** [comment]
It's an interesting question though. With the newest compiler is it still necessary to set `pragma experimental ABIEncoderV2` to compile the contracts?

**Comment by boolafish** [comment]
haha not sure, but on my VSCode IDE the solidity would complain if not adding that and I am using "latest" version on the solidity extension. (I am not sure how latest the IDE extension is using though)

**Comment by kevsul** [comment]
Yes, it is still necessary with the latest version (5.0.34).
For me, it's solc that gives the warning about it when compiling:
```
 Warning: Experimental features are turned on. Do not use experimental features on live deployments.
pragma experimental ABIEncoderV2;
^-------------------------------^
```
I guess it will always be there until ABIEncoderV2 becomes non-experimental
