### ISSUE TITLE
Separation deployer from maintainer addresses

### ISSUE THREAD

**Issue by pnowosie** [omisego/plasma-contracts#242]
Continues on #233

## Terminology
- __Operator__ - organization, not an Ethereum address which holds other addresses
- __Authority__ - Ethereum address used exclusively to submit plasma blocks, requires `nonce = 0` as noted below.
- __Deployer__ - Ethereum address used to deploy Plasma framework for the first time
- __Maintainer__ - (aka __Operated.operator__) Ethereum address (can be the same as deployer or Multisig contract) that is allowed to register upgrades (tx types, output types, vaults, exit games, ...)

## Currently implemented
Separation `maintainer - authority` in #233
Maintainer address which can register `PlasmaFramework` components is passed as `msg.sender` during deployment. There were effort to separate `maintainer - deployer` addresses in #239 - but we found out that we need to untangle inheritance dependencies first (__TODO__: mention task :question: )

## Deployment process
Plasma Framework constructor accepts Maintainer address as a parameter. During deployment 
Deployer address sets Maintainer address. It could be the same address as Deployer for test networks or dedicated address (possibly multisig) responsible for registering components.

Note that: __Authority address is unset yet__. Deployer address can be throwaway address it isn't stored or verified anywhere in the contract.

Maintainer address register appropriate components (sets addresses of component contracts to the registries). Component contracts can be deployed by Deployer or Maintainer it does not matter, but only Maintainer can run `register...` functions on framework.

Authority address sends __its very first__ transaction that calls `BlockController.init()` function. This function sets a caller address as Authority address in `BlockController` which allows for block submission and sets a Authority address nonce - so the Plasma blocks numbers will correspond to the address nonces (`1000 * nonce = blknum`).

**Comment by boolafish** [comment]
depends on whether the migration script goes first or not, but might need to change the migration script to reflect the decoupling of addresses.

**Comment by boolafish** [comment]
ref #304
