### ISSUE TITLE
Make getting ids for standard and in-flight exits public

### ISSUE THREAD

**Issue by pgebal** [omisego/plasma-contracts#243]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Current Behavior
Function for getting exit ids are internal and can be used in contract only.

## Expected Behavior
We want to have this functions public so a user knowing transaction bytes can get it's exit id

**Comment by boolafish** [comment]
we do have wrapper contracts though, would that not be enough?

**Comment by pgebal** [comment]
@boolafish yes, basically I just moved it out from mocks folder + did some renaming
