### ISSUE TITLE
Reduce code duplication in Exit games

### ISSUE THREAD

**Issue by pnowosie** [omisego/plasma-contracts#253]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Current Behavior
Current `Router <-> Controllers` approach reduced amount of gas needed to deploy IFE exit games but unfortunately contributes to code duplication: E.g. all controllers first need to fetch exit game from map and require it exists.

## Expected Behavior

Consider better approach

**Comment by boolafish** [comment]
Since we code freeze for audit now, this is probably no doable anymore. Closing this
