### ISSUE TITLE
`TxPosLib` library HAS TO be removed !!!

### ISSUE THREAD

**Issue by pnowosie** [omisego/plasma-contracts#254]
If I understand `RootChain.sol` correctly there never be a mention of `Transaction position` used the way `TxPosLib` computes. Everywhere `TxoPos == Transaction Output position` was used even there where `oindex` was ignored or assumed to be zero.

There is only one place where RootChain's `getTxPos` was used and it's `getStandardExitPriority` where a lot information is packed into bignum with bit operations :face_with_head_bandage: 

Therefore `TxPosLib` shouldn't be exposed publicitly as it makes confusion and misleads to never used concept.  Also we would want to rename all confusing `TxPos` to `TxoPos` - to make them more clear. 

Also there might be a good idea to make broader use of UtxoPosLib.UtxoPos structure in the code.
So external functions would accept uint256 utxoPos value, which will be converted to the :point_up: UtxoPos struct and passed in that form only. Eg. also to the merkle Lib and so... 

How about ExitData stores structure instead of simple uint256 :question:

**Comment by boolafish** [comment]
I actually think it was implemented wrong, at least not as intentional in `RootChain.sol` though.

See my comments in the PR: https://github.com/omisego/plasma-contracts/pull/252#discussion_r321729009

**Comment by pnowosie** [comment]
> Also, whenever we are doing merkle proof check, we are only checking the `blockNum + txIndex` is correct (that is actually the info of `txPos`), as `outputIndex` is not checked there.

Obviously one doesn't need `oindex` value to precisely knew Tx position which is used for merkle proof. However if we allow contract to accept UtxoPos in few places and TxPos in some other places we're asking that someone will finally compare to uint256 number to check which position is older - whatever huge TxPos will be it will be always smaller than UtxoPos.

**Comment by boolafish** [comment]
As a successful criteria of this issue, we need to solve:
1. Whether we'd like to pass in `txPos` or `utxoPos` in canonicity challenge
1. make sure we are consistent in var names in code, see comment: https://github.com/omisego/plasma-contracts/pull/252#discussion_r321783002
