### ISSUE TITLE
Rethink how we handle vault updates

### ISSUE THREAD

**Issue by pgebal** [omisego/plasma-contracts#262]
## Description
When solving issue #260 I put events code into specific vaults. It introduced some code duplication that we can remove later (and register new vaults with updated code) and that raised questions:
How to upgrade a specific vault (for example ETH vault)? Can we exit from transaction that spends funds from a retired vault? How to do it?

**Comment by boolafish** [comment]
>  Can we exit from transaction that spends funds from a retired vault

We don't have plan to retire a vault atm. Current upgrade of same ERC contract vault relies on the update of verifier.

**Comment by pik694** [comment]
Refers #261

**Comment by paulperegud** [comment]
Here an idea - you don't retire vault. You define currency as a pair {token_standard, token_contract} - thus you never would mix funds from two different vaults even if they come from the same XYZ token. This would prevent a situation when vault might become insolvent due to people depositing token into one vault and withdrawing it from other vault.

**Comment by pgebal** [comment]
@boolafish you are right. I didn't understand it.
Now my understanding is that, whenever we introduce a new vault, we would also have to introduce a tx type and spending conditions that forbids to spend funds from "older" vault in new tx types. User would have a choice:

**Comment by boolafish** [comment]
[Some brain dump]

### Definition
From @paulperegud 's writing:
First, define output as following tuple:
```
Output_guard - ....
Token_standard - uint
Token_contract_address - address
Standard_specific_data - bytes
```
I understand the proposal as having three things:
1. `token_standard`: this is probably the same thing as `vault_id` that we currently kinda has but never used. It's 1:1 relationship with vault.
1. `token_contract_address`: this is the ERC implementation contract address. Currently it is named `token` in our code.
1. `standard_specific_data`: some data specific to the ERC protocol. eg. ERC20 it would be `amount`, `token`. Though `Owner` is part of the necessary data for vault, we make it stands outside of the standard specific data as it is handle on `output_guard`.

### What needs to be changed
1. Tx format (new output structure)
1. Vault api. Should use `standard_specific_data` instead.
1. ExitGameController should have a exit queue per (`token_standard`, `token_contract_address`) pair instead. (Currently only per `token_contract_address`)

**Comment by boolafish** [comment]
related to #282

**Comment by boolafish** [comment]
closing this as final decision is made in #282 
https://github.com/omisego/plasma-contracts/issues/282#issuecomment-535429760
