### ISSUE TITLE
Do not require transaction to have inputs or outputs

### ISSUE THREAD

**Issue by pgebal** [omisego/plasma-contracts#265]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Current Behavior
We expect transaction to have at least one input and output. Requirement for having at least one input was introduced by me without a concrete reason. As previous version of contracts do not have that requirement we can revert that change.

It  should be discussed if it's a good idea for transaction to have 0 outputs. Currently we go with 0 outputs for compatibility with previous version of contract and elixir-omg. 

## Expected Behavior
It is not required that a transaction has inputs or outputs.

**Comment by boolafish** [comment]
let's track the remaining at #275
