### ISSUE TITLE
Basic e2e tests for IFE flow

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#268]
### Why
We have this for SE, but we didn't start our tests suite with the e2e ones for IFE when developing. Thus we should have some as a start and verifies whether all functions works together or not.

### Successful Criteria
- Come up with a test plan
- Have some basic e2e tests covers the test plan

**Comment by pdobacz** [comment]
wait, I'm confused, those tests exist in the Python test suite (and existed for `RootChain.sol`). We're plugging this old test suite into the `PlasmaFramework.sol` contracts now, aren't we?

**Comment by boolafish** [comment]
yeah, we are porting those to give us some confidence as a short term solution but my understanding is that we will not be continuously adding new tests to that test suite. It's more like port it once and we will only do some basic maintenance on that and gradually deprecate/port to truffle  as time goes.

But anyway, this task is just asking for a really basic ones, some basic happy cases to make sure existing codes are really working then we can start audit. We can port the existing python tests cases while audit process goes in my opinion (if it is not ready when we start audit).

**Comment by pik694** [comment]
I will be starting IFE test in the following days, I will keep you updated.

**Comment by boolafish** [comment]
I think during one PR of @pgebal there is a really simple e2e test now for IFE, closing this
