### ISSUE TITLE
Integration specifications 

### ISSUE THREAD

**Issue by InoMurko** [omisego/plasma-contracts#272]
In order for other implementation teams to use plasma-contracts correctly and successfully we need to provide an `integration document`. 

## Issue Type 
```
[ ] bug report
[x] feature request
```

## Current Behavior
Not aware of any existing technical specs.

## Expected Behavior
Similar to
https://stripe.com/docs/payments
https://www.emvco.com/emv-technologies/src/ (scroll to specifications)

## Steps to Reproduce
/

## Suggested Fix
/

## System Specs
/

**Comment by InoMurko** [comment]
This should specifically address the ALD implementation.

**Comment by boolafish** [comment]
[NOTE]
sigh, I wasn't able to find a way to use the following two tools to automatically generate the doc but worth note it here: (and hopefully some smart people can find out some way to do this clever XDD)

1. https://github.com/OpenZeppelin/solidity-docgen
1. https://github.com/DigixGlobal/doxity

I think current issue is that truffle uses solc-js and the tool uses solc. We have code importing external libraries (eg. from openzeppling) and solc would fail on compilation.

**Comment by Pongch** [comment]
Hey, let's continue conversation on this GH issue here @kevsul . I believe it was @paulperegud who worked on the integration spec prior to this. Could you help take a look at what we have thus far and what is necessary to have a) brief walkthrough of all flows and b) details on the expected API call req and response ?

**Comment by boolafish** [comment]
GOOOD NEWS!!!!! Finally find one tool that does not need to do the stupid compilation :p

https://github.com/CYBRToken/solidoc

I tried it locally and it was able to auto generate the doc files from code documentation!!

**Comment by thec00n** [comment]
Very nice @boolafish.

I think we can use this for all kinds higher level documentation to reference to. Can we get this merged?
