### ISSUE TITLE
Enforce CI to fail when solhint has warning

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#280]
## Issue Type 

```
[] bug report
[x] feature request
```

## Current Behavior
Though CI checks the solhint, but it doesn't fail when there is warning.
eg. https://circleci.com/gh/omisego/plasma-contracts/2352?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

## Expected Behavior
CI should fail when warning exists.

**Comment by kevsul** [comment]
This is due to a bug in solhint: https://github.com/protofire/solhint/issues/159

**Comment by boolafish** [comment]
Wow you’re really solhint master.....I see you fix another bug as well 💪💪

**Comment by thec00n** [comment]
Nice @kevsul

**Comment by boolafish** [comment]
Looks like @kevsul 's PR is merged and new version is released in 2.3.0: https://github.com/protofire/solhint/commits/master

And we've upgraded it to 2.3.0 now

**Comment by boolafish** [comment]
tested locally, it now throws error when running `npm run linter-sol` if there is warning
