### ISSUE TITLE
Return to exit priority and exit id calculation schema from RootChain 

### ISSUE THREAD

**Issue by pik694** [omisego/plasma-contracts#283]
We should return to the exit priority calculation schema that was used in RootChain contract, as we should favor the solutions that do not change the API,  there is also no apparent reason to stay with the current schema, moreover the current schema costs more gas.

### RootChain schema
Exit priority used to be computed with the following schema:
```
|255                     214|213     160|159                      0|
|---------------------------|-----------|--------------------------|
|    exitable timestamp     | tx pos    |         exit id          |
```

### Current schema
```
|255                     192|191              64|63    0|
|---------------------------|-------------------|-------|
|    exitable timestamp     |    tx position    | nonce |
```

The changes of the exit priority does not affect the priority itself, as the exitable timestamp is still the most significant field, but such the new schema changes the API (the old priority differs from the new one givent the same transaction) and the current schema enforces to introduce a mapping from exit priority to exit id, in order to process the exit.   

The field nonce is stored in the `ExitGameController` contract and is updated each enqueuing - which increases the overall cost of `startExit` transaction.

# priority -> Exit mapping in ExitGameController
Having changed the exit priority, we can extract exit id directly from the priority, therefore the `mapping (uint256 => Exit) public exits;` can be changed as follows: `mapping (uint256 => IExitProcessor) public exits`, which is also more gas efficient.

**Comment by boolafish** [comment]
> Exit priority used to be computed with the following schema:

I think your graph is wrong compare to the code:
```
return ((getExitableTimestamp(_utxoPos) << 214) | (tx_pos << 160)) | _exitId;
```
It doesn't have full space for exitId previously actually.
From the code document:
```
 *   Anatomy of returned value, most significant bits first
     *   42 bits - timestamp (exitable_at); unix timestamp fits into 32 bits
     *   54 bits - blknum * 10^9 + txindex; to represent all utxo for 10 years we need only 54 bits
     *   8 bits - oindex; set to zero for in-flight tx
     *   1 bit - in-flight flag
     *   151 bit - tx hash
```

we'd need to re-desing for the oindex part as we've bumped the size.

**Comment by boolafish** [comment]
As for the issue of using `exitId` in `processEixts` that you've mentioned in slack is separate from this. It is still doable with current mechanism if with want.

**Comment by pik694** [comment]
>  I think your graph is wrong compare to the code

Yes, you are right - I made it from my memory - which is apparently poor.

**Comment by pik694** [comment]
Having analyzed both exit priority and exit id structure from RootChain, we came to a conclusion that there is not enough place for outputs in exit id. 
Exit id consists of (in order of most significant bits):
- 8-bits oindex
- 1-bit IFE flag
- 150-bits of tx hash.

oindex has only 8 bits, but it is a value from range 0-10,000; which means that it should have at least 14-bits. 

In order to fix this issue, we will add the required 6 bits to oindex by moving ife flag to right and subtracting the 6-bits from tx hash.
The new exit id schema will be as follows:
- 14-bits oindex
- 1 bit IFE flag
- 144-bits tx hash.

**Comment by pik694** [comment]
# Exit id length
While going deeper into the issue, we saw that we use `uint192` to store `exit id`, while we are actually using and are prepared for 160-bits only. 

We decided to tighten the type of `exit id` to 160 bits only.

The previous type might have been deceiving and error-prone in the future.

**Comment by boolafish** [comment]
@pik694, I peaked into your [commit](https://github.com/omisego/plasma-contracts/commit/74034be01ccf9e34823d2a60dad5482dc0b97d3d), I am actually lost why we can use only 8 bits for output index and bring back the limitation of 255? 

But if that's just a WIP thing, I will wait until the PR then.

**Comment by pik694** [comment]
We have 256-bits of exit priority, which consists of 3 major parts: exitable timestamp, tx position and exit id.
Now, the lengths of the first two fields are roughly calculated and should be:
- exitable timestamp - 42 bits (actually more than we need);
-  tx pos - 54 bits.
 
https://github.com/omisego/plasma-contracts/blob/82b4ea7327106837defeb7fb58ad10503ba6c57f/plasma_framework/contracts/src/framework/utils/ExitPriority.sol#L13

The above means that we are left with only 160 bits; but we are free to use each and every bit, if only we guarantee that there will be no collisions between exits.

As the issue is meant to revert to `RootChain` exit priority and exit id schemas, I took the exit id schema from the previous contract - 8 bits of oindex, 1-bit ife flag, 151-bits tx hash.
As you can see we have only 8 bits for oindex, which means that if we create a tx with at least 256, we will have a collision between the 0th and 256th output.

I must have tightened  the length of exit id as otherwise the 256th output would overwrite tx position. 

Please, note that this limitation is simply limitation of the exit id, we are now using. In the future we can provide a new exit id schema in order to increase the limitation.

**Comment by pik694** [comment]
I may have changed the exit id schema to be compatible with 10,000-outputs transactions. The roughly schema following:
- 14-bits oindex;
- 1-bit ife flag;
- 145-bits tx hash.

I discussed the topic with @pdobacz and we decided to keep it simple for now and use the schema we used to use.

**Comment by boolafish** [comment]
> In the future we can provide a new exit id schema in order to increase the limitation.

This is actually something that's not that great using this design. All new exit id schema need to take old existing exit id schema into consideration whether they are gonna collide or not, which adds extra design concern and complexity. But anyway, probably not a huge concern.

> I may have changed the exit id schema to be compatible with 10,000-outputs transactions

I just come up with a better (?) idea, I think the following would be nice for SE. 
```
- 1-bit ife flag
- 159 bit left-most 159 bits of outputId
```
This only drop a bit from the ethereum assumption of address being 160 bits plus `outputId` is something baked into `PlasmaFramework` already.

**Comment by pik694** [comment]
@boolafish Yours is another option, but what is an `outputId` in case of an IFE?

**Comment by boolafish** [comment]
Just....keep IFE exitId as it is? It is just a hash of `txBytes` plus a flag now, so probably just

```
1-bit ife flag
159-bits left-most 159 bits of hash(txBytes)
```

**Comment by pik694** [comment]
Please note that nowadays `exitId` includes `oindex`, which in case of IFE is not necessary (zeroed), as we process IFEs as a whole tx. In case of a SE, each output from a tx is an another exit, which means that using a tx hash is to little to tell which output is to exit.

**Comment by pik694** [comment]
Which shows that there is no generic solution that may work out of the box. We can probably move the discussion to an another issue, as I believe that this topic probably is out of the scope of this issue.
