### ISSUE TITLE
Create consistent documentation using the NatSpec format for contracts, functions, modifiers, events and state variable declarations 

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#284]
## Issue Type 

```
[x ] feature request
```

## Current Behavior 
A lot of parts of the contract system are not documented. 

## Expected Behavior
In some parts we started to use the NatSpec format for example here: https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/framework/ExitGameController.sol#L65-L74

I propose that we create documentation for all contracts, functions, modifiers, events and state variable declarations across the entire contract system.

**Comment by thec00n** [comment]
In order to get started I would suggest the following documentation policy on what definitions should be documented:

- all public/external functions
- internal/private functions optional (appreciated if complexity is high)
- state variable declarations
- contracts (at least the ones that are directly deployed)

**Comment by boolafish** [comment]
TODO List:

- [ ] exits/interfaces/
- [ ] exits/models/
- [ ] exits/payments/controllers/
- [ ] exits/payment/routuers/
- [ ] exits/payment/outputGuardHandlers/
- [ ] exits/payment/spendingConditions/
- [ ] exits/payment/xxx.sol
- [ ] exits/registries/
- [ ] exits/utils/
- [ ] framework/interfaces/
- [ ] framework/models/
- [ ] framework/registries/
- [ ] framework/utils/
- [ ] framework/xxx.sol
- [ ] transactions/
- [ ] utils/
- [ ] vaults/
