### ISSUE TITLE
Fix ALD code non-able to compile with optimizer on

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#286]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
`plasma_framework/`  code cannot compile with optimizer on.

## Expected Behavior
Should be able to compile.

## Steps to Reproduce
in `truffle-config.js`, turn on the optimizer:
```
          settings: {          // See the solidity docs for advice about optimization and evmVersion
                optimizer: {
                    enabled: true,
                    runs: 1,
                },
                evmVersion: "byzantium",
            },
```
And then run: `truffle compile`.
It would throw the error:
```
InternalCompilerError: Assembly exception for bytecode

Compilation failed. See above.
Truffle v5.0.21 (core: 5.0.21)
Node v9.2.1
```

## Suggested Fix
So far, I wasn't able to find a fix yet. However, I can pin-point the file that causes the error is `PaymentStandardExitRouterMock` (by deleting file, compile and passes). Luckily it's just the mock that causes this.

**Comment by boolafish** [comment]
[Note]

So if we remove the part
```
      PaymentStandardExitRouter(
            plasmaFramework,
            ethVault,
            erc20Vault,
            outputGuardHandlerRegistry,
            spendingConditionRegistry
        )
```
in constructor it would compile.....however I don't know why and how to solve yet XDD

**Comment by pdobacz** [comment]
Hi, not sure if this helps, but with `solc v0.5.11` and contracts from commit `67b90e5175cd1e4d503ad0160cb069565ef91136`, branch: `150_python_tests_on_plasma_framework` it compiles fine with optimizer on, 1 run:

My invocation `"~/Downloads/solc-static-linux openzeppelin-solidity=openzeppelin_solidity --overwrite --abi --bin --optimize --optimize-runs 1 -o ...`

**Comment by pdobacz** [comment]
oh, I just after noticed that it's a single file that fails, which I am not compiling :man_facepalming:, oh well, so scratch my comment
