### ISSUE TITLE
Consider combining logic of deposit verifier with logic of withdrawal in a single contract

### ISSUE THREAD

**Issue by paulperegud** [omisego/plasma-contracts#295]
Consider combining logic of deposit verifier with logic of withdrawal in a single contract. Both Erc20Vault and iErc20DepositVerifier are ERC20 specific. What do we get by splitting only part of it outside?

Separation of vault logic from vault storage could be useful, but in this case we separate only part of vault logic. Also, I believe, we've established that vault once deployed will not be upgraded.

Lets keep it simple where possible.

**Comment by paulperegud** [comment]
> Deposit Verifier is there to support upgrade to arbitrary tx types.

One possible way of dealing with this is allowing depositor to choose output type. This would lift a need to do a transaction moving funds to `V2`. But that solution would prevent us from upgrading tx structure.

**Comment by boolafish** [comment]
closing this as final decision is made in #282 
https://github.com/omisego/plasma-contracts/issues/282#issuecomment-535429760
