### ISSUE TITLE
Use SafeMath for all tainted inputs   

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#296]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior
`SafeMath` is not consistently used across the contract system. Input from malicious users could potentially overflow or underflow variables and change the business logic in undesirable ways. 

In the following example this could happen theoretically when calculating the sum of outputs. While this is unlikely to happen practically in this case it still highlights the importance of taking every precaution. Further information on the nature of the issue can be found at https://consensys.github.io/smart-contract-best-practices/known_attacks/#integer-overflow-and-underflow or for examples check https://smartcontractsecurity.github.io/SWC-registry/docs/SWC-101. 

https://github.com/omisego/plasma-contracts/blob/3eda481acb53ca74ff2420d73eb1fe5528e1eb6a/plasma_framework/contracts/src/exits/payment/PaymentTransactionStateTransitionVerifier.sol#L107-L113 

## Suggested Fix
Review all arithmetic operations in the contract system and replace them with safe alternatives from OpenZeppelin's SafeMath library. Any arithmetic operation that contains at least one tainted value (can be influenced by any user in the system) should be changed to use the safe version.

**Comment by boolafish** [comment]
Before I forget, but in a call with @thec00n he mentioned this code has issue too:

https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/contracts/src/utils/UtxoPosLib.sol#L27

**Comment by thec00n** [comment]
Can we still refactor this line to use SafeMath @pgebal ?

**Comment by boolafish** [comment]
FYI: I think for the `BondSize` I've questioned about using SafeMath and here was the discussion:
https://github.com/omisego/plasma-contracts/pull/235#discussion_r319541240

@kevsul argued that would be unnecessary there. BTW, I just want to bring the discussion open again so we can all learn on what should be a good default coding practice to us.

**Comment by thec00n** [comment]
I think using SafeMath here is a conservative choice and it is immediately clear that the value can never overflow, so it helps also with the readability of the code. Are the two uint256 casts really cheaper than using the SafeMath function? I would like to encourage everyone to use SafeMath in cases where it takes longer than 10 minutes between people to agree on if something can overflow or not.

**Comment by boolafish** [comment]
I end up finding using `SafeMath` here does not really make sense as it only protects overflow with `uint256`. However, if we do care about overflow we should be protecting with `uint128` that is the real limit on the bond size. Using SafeMath would become misleading and give wrong impression that it is "safe".

What I do find it interesting is that current code cast it to `uint256` before compare, this actually allows the ability to update the bond size to `2^128 - 1` without worrying overflowing on the other side of `currentBondSize * _self.upperBoundMultiplier`. As a. result, I decide to add test showing that feature instead.

**Comment by thec00n** [comment]
Yes you are right @boolafish in regards `SafeMath`.

I will check out the tests when I get a chance.

**Comment by pgebal** [comment]
@thec00n @boolafish I didn't use SafeMath there because of issues raised by @boolafish. Sorry that I didn't reply earlier. I missed that discussion.
