### ISSUE TITLE
Understand ExitId security design

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#299]
### Note
This is just for discussion and make sure we justify and understand ourselves for using shorter hashed value of txBytes in `ExitId`.

This is the current `ExitId` design:

```
*     Anatomy of returned value, most significant bits first:
     *     16 bits - output index
     *     1 bit - in-flight flag (0 for standard exit)
     *     151 bit - hash(tx) or hash(tx|utxo) for deposit
```

What I would like to discuss is the 151 bits part. In general, we have 160 bits assumption as Ethereum address is 160 bit. However, for using lower bits we probably would like some justification and security analysis saying what's the assumption we are on when using this.

**warning: the above design might be changed after: https://github.com/omisego/plasma-contracts/issues/283**

### Successful criteria
- Make sure we understand what the assumption of using shorter bits
- Document it to the security document

**Comment by thec00n** [comment]
Tracking this on an internal repo
