### ISSUE TITLE
Create test coverage reports

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#300]
## Issue Type 

```
[ ] bug report
[ x ] feature request
```

## Current Behavior
It is not possible to measure test coverage. 

## Suggested Fix
Use e.g. solidity-coverage to create test coverage reports and have an online visualization of the reports e.g. www.coveralls.io. 

## Motivation for Change
It is crucial to understand test coverage across the smart contracts and the gaps that might exist in them. As part of the audit readiness requirements we would like to get close to 100% test coverage once the audits start.

**Comment by boolafish** [comment]
done in #310
