### ISSUE TITLE
Refactor controls for administrative roles to reflect role scheme 

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#304]
## Issue Type 
```
[ ] bug report
[ X ] feature request
```

## Current Behavior
The following administrative roles are conceptually agreed upon but have not been implemented consistently across the contract system. 

- Authority: EOA used exclusively to submit plasma block hashes to the root chain. 
- Deployer: EOA used to deploy all root chain contracts. 
- Maintainer: MultiSig wallet that is allowed to initiate upgrades/updates of specific parts of the root chain contracts. Can also update the exit bond size. 
- Contract: A root chain contract that is authorized to call specific functions in other root chain contracts.

ref: #242 

## Suggested Fix

Suggestions are made as follows on a per contract basis. 

### Operated

- [ ] Rename the contract `Operated` to `Maintainable` in order to make it clear for which role it is used for.  

```
contract Maintainable {
    address public maintainer;

    constructor() public {
        maintainer = msg.sender;
    }

    modifier onlyMaintainer() {
        require(msg.sender == maintainer, "Can only be called by maintainer");
        _;
    }

}
```

### EthVault and Erc20Vault 

Todo: 
- [ ] Rename `Operated` to `Maintainable`
- [ ] Set Maintainer during contract creation 
- [ ] Use `onlyMaintainer` to control access to register new DepositVerifier 

### PlasmaFramework

Todo: 
- [ ] Rename `Operated` to `Maintainable`
- [x] The upgrade mechanism `registerExitGame` and `registerVault` for `VaultRegistry` and `ExitGameRegistry`  is inline with the main product requirements of being able to add components after `MIN_EXIT_PERIOD` has passed.  
- [ ] Instead of inlining the check if the function `submitBlock` is called from Authority create a modifier onlyAuthority() so it's aligned with the scheme of using modifiers for access checks. 
- [ ] The `initAuthority()` function is susceptible to front running and can be called by anyone after contract creation until it is called for the first time. I propose to remove `initAuthority()` and `setAuthority()` and set `authority` during contract creation. 

### PriorityQueue

Todo:
- [ ]  Remove the Ownable contract. 
- [ ] Introduce a new variable `plasmaFramework` that is set at contract creation.
- [ ] Create a new modifier `onlyFromPlasmaFramework` that restricts calling the functions `insert` and `delMin`. 

### PaymentExitGame

Todo: 
- [ ] Remove the contract `OnlyFromAddress` and instead introduce a modifier `onlyFromPlasmaFramework` that checks if `processExit` is in fact called by PlasmaFramework
- [ ] Change the modifier for `updateStartStandardExitBondSize` to `onlyMaintainer()`. Set maintainer during contract creation. 

### OutputGuardHandlerRegistry

Todo: 
- [ ]  Add inline documentation that provides the background on that the owner is deployer and that the ownernship is revoked after registering OutputGuardHandlers.

### SpendingConditionRegistry

Todo: 
- [ ]  Add inline documentation that provides the background on that the owner is deployer and that the ownernship is revoked after registering SpendingConditions.

**Comment by boolafish** [comment]
> EOA used...

A n00bie question, what is EOA?

> Remove the Ownable contract and use Mainainable instead

For OutputGuardHandlerRegistry and SpendingConditionRegistry then we need to some alternative way to freeze the functionality. It has `renounceOwnership` for free at this moment by using `Ownable`.

**Comment by thec00n** [comment]
:) Externally Owned Contract ... I got like three people asking me what that is. 

I was under the impression that the maintainer can upgrade this. Just looking at the proposed deployment https://github.com/omisego/plasma-contracts/blob/60ca330ab08d1c4a8bd57e067e90851b72539fab/plasma_framework/migrations/5_deploy_and_register_payment_exit_game.js#L77 this does not seem to be the case. `registerSpendingCondition` seem to suggest that you can register new SpendingCondition contracts based on a key?

**Comment by boolafish** [comment]
> I was under the impression that the maintainer can upgrade this

yes, for a short while of span, and then its ownership is renounced immediately.

https://github.com/omisego/plasma-contracts/blob/60ca330ab08d1c4a8bd57e067e90851b72539fab/plasma_framework/migrations/5_deploy_and_register_payment_exit_game.js#L81

> seems to work in a similar way.

Yeah, they both have the same concept of design.

**Comment by thec00n** [comment]
If that's the case then why do we need `OutputGuardHandlerRegistry` and `SpendingConditionRegistry`. We could just wire `PaymentOutputToPaymentTxCondition` and `PaymentOutputGuardHandler` into `PaymentExitGame`?

**Comment by boolafish** [comment]
The `PaymentTxV2` would be able to be spent in multiple transaction types (2 I guess), plus itself would have 2 output types. That's why we decoupled the dependency this way instead of direct injection.

**Comment by thec00n** [comment]
I don't understand the contract system well enough yet to know what that means. Generally speaking though in regards to registries ... A registry that will only ever hold one thing and you will never able to change or add more things seems not very meaningful.

**Comment by boolafish** [comment]
> A registry that will only ever hold one thing and you will never be able to change or add more things seems not very meaningful.

I agree. It is more of a future proofing coding and as an effort of not re-audit the PaymentExit game in the future when we introduce DEX (or sth else)

**Comment by thec00n** [comment]
@boolafish just looking at this again and the background you gave me on future developments, I think we can leave `OutputGuardHandlerRegistry` and `SpendingConditionRegistry` the way they are. Let's create some inline documentation that provides the background on who the owner is and around the lifecycle of the ownership.

**Comment by pnowosie** [comment]
> The initAuthority() function is susceptible to front running ... I propose to remove initAuthority() and ... set authority during contract creation.

This needs to be handled also on elixir-omg as we have [calc_nonce](https://github.com/omisego/elixir-omg/blob/b1a1844a87617bb286612006942fef7b24dd12e7/apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex#L386) and there is probably check in Watcher I cannot find atm...

**Comment by thec00n** [comment]
@pnowosie it be great if someone could drive this and coordinate the changes with the elixir-omg team.

**Comment by pnowosie** [comment]
> This needs to be handled also on elixir-omg as we have calc_nonce and
> @thec00n:  it be great if someone could drive this and coordinate the changes with the elixir-omg team.

Well changes in elixir-omg can be avoided as well if we agree that authority address align to the requirements `elixir-omg` sets. 
This means that `nonce` of the Authority address HAS TO correspond to the OMG Network block numbers: `1000 * nonce == blknum`

Assuming that Authority address is fresh generated then without `initAuthority` it needs to send 1 successful transaction on Ethereum to comply :point_up: requirements and be able to send "block" transactions.

@pdobacz @boolafish you thoughts :question:

**Comment by pdobacz** [comment]
>  it needs to send 1 successful transaction on Ethereum to comply
just a quick not that it has to be any transaction, not even a successful one, so that we enjoy the not-off-by-one nonce-blknum relationship (which is not paramount maybe but I think quite nice, makes diagnosing problems significantly easier on the brain). `nonce=1` start for `authority` is not enforced anymore then, so it's slightly easier to miss.

**Comment by pnowosie** [comment]
>  so that we enjoy the not-off-by-one nonce-blknum relationship

I'm afraid it's just making our lives easier [it won't work otherwise](https://github.com/omisego/elixir-omg/blob/3fbb3f1ed54cc2f9eb60d3863b33adbe53f6f799/apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex#L387)

**Comment by pdobacz** [comment]
OK, my above comment produced some confusion. To clarify:

1. I'm in favor of keeping the nonce-to-blknum relationship, unless brings some larger problems to the table. It is useful to have 1000 * nonce == blknum
2. I understand there's a need for the authority to not have to call `initAuthority` anymore. If this is the case, we'll need to remember to bump the `authority` nonce to have (1.). That bump could be any mined tx coming out of `authority`. This bump is then "not enforced", I'll edit the above comment to say "not enforced in the contract"

**Comment by pnowosie** [comment]
OK, so the options we have are:

1. [Contract only]: Remove `initAuthority()` as proposed but comply to the rule `1000 * nonce == blknum` and then avoid elixir-omg changes
1. [Contract, ch-ch & Watcher]: as above and then hunt for all the places the :point_up: rule is in force and fix it 
1. [Naive]: Acknowledge the possible "front running" issue and make sure deployment scripts call `initAuthority()` just after deployment to lower the severity of the threat.

(CC @thec00n, @boolafish )

**Comment by thec00n** [comment]
I am ok with 1. and 2. As you might guess I am not a fan of 3.

**Comment by boolafish** [comment]
I think to be able to handle this #242 to separate maintainer from deployer, we cannot use that `Maintainable` style modifier directly due to inheritance diamond issue: https://github.com/omisego/plasma-contracts/pull/239#issuecomment-527825228

Some options in my mind:
1. Proper dependency injection and untangle the inheritance. However, this would be a huge change and need to re-write the public functions to wrap the call to the injected dependency.
1. reuse the `OnlyFromAddress` and inject the address to each contract that need protection. I think @thec00n has the recommendation of remove `OnlyFromAddress` to be something more specific. However, when it is used, it is pretty readable eg. `onlyFrom(address(plasmaFramework))`. The down side would be the revert message would be more broad without showing which actor fails. Upside is that less code to maintain. We can probably replace all `onlyXXX` to this instead.
1. Have library and custom struct + method for each address. eg.
```
library Maintainable {
    struct Maintainer {
        address actor;
    }

    function isCalledByMaintainer(Maintainer memory self) internal {
        require(msg.sender == self.actor, "Can only be called by maintainer");
    }
}
```
and then we inject the `Maintainable.Maintaner maintainer` to each function needed. Remove `modifier` and call the `isCalledByMaintainer` instead.

**Comment by boolafish** [comment]
> OK, so the options we have are:

I have one more idea, we can store the authority address during constructor but we still need another function to activate the authority address. Basically `initAuthority()` -> `activateAuthority()` (and would verify `msg.sender==storedAuthority`) so everything looks good and making sense though it is really just an action for an action......XD

**Comment by thec00n** [comment]
@boolafish I don't understand `... but we still need another function to activate the authority address.` Why do we need that?

**Comment by boolafish** [comment]
It’s really just to comply the rule to do an action to make it nonce starting with one. And by checking with the value during deployment, we can avoid front runner

**Comment by thec00n** [comment]
If it's just about increasing the nonce then why don't we just simply perform a transaction? Why do we need an extra function for that?

**Comment by thec00n** [comment]
As discussed with @boolafish  I am proposing to refactor Blockcontroller (see also https://gist.github.com/thec00n/494d04a2393fcd6aa80c6d2509d2c764#file-blockcontroller-sol-L12-L47) to set `authority` during contract creation. The child chain needs to trigger the first transaction and call `activateChildChain` (from the authority address). The function can only be called once and emits the ChildChainActive event. This will also set nonce to 1 and then the child chain can start to produce blocks. FYI @jbunce is working on a solution that will not require us to store the private key on the child chain system. The child chain will request another hardened system to sign transactions for `submitBlock()` and activateChildChain()` but will not allow any other calls to PlasmaFramwork or any other contract.
