### ISSUE TITLE
Rethink ExitID schema

### ISSUE THREAD

**Issue by pik694** [omisego/plasma-contracts#305]
When resolving issue #283, we decided that we should rethink exit id, in order to be a little bit more future-proof and be capable of operating on transactions with 10,000 outputs.

Please refer to discussion on `exit id` in #283. 
@boolafish proposed to split `exit id` into two fields:
- 1-bit IFE flag;
- 159-bits ife id / se id.

Where IFE id would be:
- 159 most left bits of hash(in-flight tx bytes)

And SE id:
- 159 most left bits of `outputId`.

**Comment by paulperegud** [comment]
Initial idea was: we can find all potentially relevant SE on inputs if we have just IFE exitId and vice-versa.

Later, "thomalla heist" happened and now we have to have a table of exited outputs. This solves a problem of SE<>IFE interaction on different stage of exit processing.

Potentially useful links:
https://github.com/omisego/plasma-contracts/issues/110#issuecomment-499419571
https://github.com/omisego/elixir-omg/blob/master/docs/standard_vs_in_flight_exits_interaction.md
https://github.com/omisego/plasma-contracts/issues/102#issuecomment-495809967

**Comment by boolafish** [comment]
let me put this as audit blocker. IMO, if we are dropping nonce for exit priority, then we would want to have a single exit id schema otherwise it would be too much of mind complexity verifying each exit id are impossible to collide with each other.

**Comment by boolafish** [comment]
Given the amount of time, we decide to not go forward this and just introduce new exitId that we makes sure it would not collide with existing one if we need that.
