### ISSUE TITLE
State variable shadowing in PlasmaFramework

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#309]
## Issue Type 

```
[ x] bug report
[ ] feature request
```

## Current Behavior
`PlasmaFramework` inherits `ExitGameRegistry` and `VaultRegistry`. Both registries define a variable that is named `_quarantine`. This is bad practice and could potentially lead to security  issues. 

More Information on state variable shadowing -> https://swcregistry.io/docs/SWC-119

## Suggested Fix
Rename the variables to `_exitGameQuarantine` and `_vaultQuarantine`.

**Comment by pgebal** [comment]
I think that's not exactly SWC-119 yet. Here we have a contract that inherits from contracts that both have _quarantine as private variable. But we may run into trouble when someone decides to change visibility, so here comes: https://github.com/omisego/plasma-contracts/pull/314

**Comment by thec00n** [comment]
@pgebal you are right about the visibility and that other contracts should not be able to access the variable. It's still good practice to have more explicit naming especially in a contract that has several base contracts.
