### ISSUE TITLE
Update Readme and cleanup repository

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#318]
## Issue Type 

```
[ ] bug report
[ x ] feature request
```

## Current Behavior
The repository contains 2 smart contract code bases, the old MVP contracts and the new MoreVP contracts. The README.md still refers to the old contracts in /contracts. 

## Suggested Fix
- Remove all contracts that are not used anymore
- Update README.md

**Comment by boolafish** [comment]
Please update the README to here first: https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/README.md

So we can deprecate the outside folder at once I guess.
