### ISSUE TITLE
Run python struct hash tests on new tx format

### ISSUE THREAD

**Issue by pik694** [omisego/plasma-contracts#329]
New tx format specifies that a tx can consist of a variable number of inputs and outputs. We should sure that the values of struct hashes integrate with the ones produced by Metamask.

The tests can be found there:
https://github.com/omisego/plasma-contracts/blob/e5c9c212de9577ffbadc69f2d897f78266cdb664/tests/utils/test_eip712_vectors.py#L8

**Comment by boolafish** [comment]
FYI: Current ALD implementation actually still hard code the length when doing EIP712 hash.

Btw, directing porting test cases to js from python might be a considerable strategy for this one too as this is pretty "unit testing" plus we don't really get more from python consider how much it breaks by the new struct data structure.

We might want a real metamask testing (even manual) sometime to make sure it really works though.

**Comment by boolafish** [comment]
I think this is done? Can you confirm @pik694 ?

**Comment by pik694** [comment]
It is indeed 🙂
