### ISSUE TITLE
Fees and input amount can be higher than output amount

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#334]
## Issue Type 

```
[ x  ] bug report
[ ] feature request
```

## Current Behavior
This is more of a question. `amountIn >= amountOut` in `isCorrectSpend` does not strictly require that all inputs are spent. To my knowledge fees are implicit and at some point the operator will decide on a fee model and not include transactions if they do not pay a sufficient fee to the operator address. If that is the case then wouldn't it still make sense to require all users to spend all inputs and wouldn't all funds (inputs) be lost if they are not included in outputs?  

https://github.com/omisego/plasma-contracts/blob/6231f702d708d1f13c3c8ca8b8e276ec08931507/plasma_framework/contracts/src/exits/payment/PaymentTransactionStateTransitionVerifier.sol#L101-L112

**Comment by kevsul** [comment]
Implicit fees means that the fee is the difference between the sum of the inputs and the sum of the outputs. The fee is not paid directly to the operator address.
So if your tx has inputs worth 1000 and outputs worth 900, then you're paying 100 as a fee. 

In other words, no funds are ever **lost** - if it's not in the outputs then it's the fee.

**Comment by thec00n** [comment]
How would an operator use the fees either on the child chain or exit them to the root chain?

**Comment by kevsul** [comment]
Up until now the idea was that there would be a special fee exit that the operator can use. 
There has been some recent discussion on this though, so it may change https://github.com/omisego/plasma-contracts/issues/165

**Comment by thec00n** [comment]
The fee part is currently proposed in https://github.com/omisego/plasma-contracts/pull/511
