### ISSUE TITLE
`PaymentExitGame.startInFlightExit` OOGs when #outputs > #inputs

### ISSUE THREAD

**Issue by pdobacz** [omisego/plasma-contracts#342]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior

When attempting to start an ife from a transaction that has #outputs > #inputs the transaction seems to be able to consume any amount of gas (when I try with 6M gas allowance it reverts consuming 5820349). Transactions that have #outputs <= #inputs work just as expected.

I haven't been able to have a proper isolated reproduction of this, but judging by Watcher's integration tests from [this revision](https://github.com/omisego/elixir-omg/commit/7ddb42b1ca011277ef14d6ad7110e6f30f1c6196), see lines: https://github.com/omisego/elixir-omg/blob/7ddb42b1ca011277ef14d6ad7110e6f30f1c6196/apps/omg_watcher/test/omg_watcher/integration/in_flight_exit_test.exs#L164-L179

Notice that `tx1` has two outputs whereas `tx2` only one. The IFE for `tx2` is started but for `tx1` is not

The data that's being sent to the contract seems healthy: https://gist.github.com/pdobacz/e0f3b872c18215d9542164ecf84e103c

## Expected Behavior

start ife should work in all combinations of ins/outs. The loop that could cause the OOG should not be possible.

## Steps to Reproduce

WIP, unless you're able to run the watcher tests, then:

```
mix test --only integration test/omg_watcher/integration/in_flight_exit_test.exs --seed 0 --trace
```

on revision cited above.

## System Specs

- python version: N/A
- pyetherem version: N/A
- environment (output of running `pip freeze`): N/A
- operating system: Linux
- solc: 0.5.11
- geth: 1.8.27

**Comment by boolafish** [comment]
Not sure related to the cause of this or not, but did find one buggy code: [here](https://github.com/omisego/plasma-contracts/blob/5dfc5eb55684b9b0f32ea3fa39573ca720de1c9f/plasma_framework/contracts/src/exits/payment/PaymentTransactionStateTransitionVerifier.sol#L43)

The array of outputs should not be the size of inputs. cc @pgebal

**Comment by pdobacz** [comment]
ah this looks like this might be it, nice catch. I can locally patch and see if problem goes away! I scanned some portion of the code to find sth like this, but it's been buried deeper. Interesting though, why would this have the effect it does? does it overwrite some memory associated with the `for` loop? ouch.

**Comment by pdobacz** [comment]
yup. Changing `new` from that line to use `transaction.outputs.length` instead makes it click! I'll let you guys do the PR-honors, to include some tests covering this.

**Comment by pgebal** [comment]
Starting with this now.
