### ISSUE TITLE
Never hit this loc in Merkle.checkMembership

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#343]
## Current Behavior

Just stumbled upon this and found it strange that we never hit this line https://coveralls.io/builds/26200700/source?filename=contracts/src/utils/Merkle.sol#L36 for computing the hash of a branch with an odd index?

**Comment by thec00n** [comment]
We need to add more tests to our test suite https://github.com/omisego/plasma-contracts/blob/d8b253d4713165101db55880655653260ec605a3/plasma_framework/test/src/utils/Merkle.test.js#L8-L48

It be great to have a Merkle Tree has N tx such that N is either in the lower range and in the upper range of 2^16 and then check valid and invalid membership.

**Comment by boolafish** [comment]
close as #365 merged and coverage for Merkle.sol has reached 100%
