### ISSUE TITLE
Potential reentrancy on processExits()

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#369]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior
`Plasmaframework.processExits()` does not have any reentrancy guard because it acts mostly like a proxy to the ExitGame contracts and all its public/external functions are protected from reentrancy. Assuming that there are multiple ExitGame contracts linked in the `Plasmaframework`:

- Could an attacker do something interesting with that?
- What are the security considerations for adding new ExitGame contracts?
- What do we need to consider for the current implementation to add new ExitGame contracts safely?

**Comment by boolafish** [comment]
@thec00n if this is not a concern anymore please close this one. I think we've solved this.
