### ISSUE TITLE
DOS / griefing attacks on calls from processExits()

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#385]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior
`processExits` is susceptible to attacks. The first scenario is a DOS  attack that would break processing of items in the `PriorityQueue`. Consider the following scenario that in a reduced version mimics how `PriorityQueue` is used for exit game.  

1.) Add items to the queue 
2.) Wait a defined period of time `minExitPeriod`
3.) Reduce the queue by N items (in order they were added) and while doing so make a call to another untrusted contract/EOA (all contracts that are not part of the deployment)

If during `removeItemsfromQueue` a contract is called that drains the entire gas stipend then  even only one item from the queue could fail and permanently lock the queue. The scenario below fails when processing two items but this depends on the amount of gas used after the failed call and how much gas was provided. Likely exiting to `GasDos` will beak the exit game queue with only one item due to more instruction being executed after a call. 

```
pragma solidity 0.5.11;

import "../../src/framework/utils/PriorityQueue.sol";

contract PriorityQueueDOS {
    
    PriorityQueue pq;
    address callee;
    uint numberOfRuns;
    
    constructor (address _callee) public {
        pq = new PriorityQueue();
        callee = _callee;
    }
    
    function addItemstoQueue(uint _numberOfRuns) public {
        numberOfRuns = _numberOfRuns;
        for (uint i=0; i<numberOfRuns; i++){
            pq.insert(1);
        }
        assert(pq.currentSize() == numberOfRuns);
    }
    
    function removeItemsfromQueue() public{
        for (uint i=0; i<numberOfRuns; i++){
            callee.call.value(0)("");
            pq.delMin();
        }    
        
        assert(pq.currentSize() == 0);
    }
}

contract GasDos {
    function () external payable{
        while (1==1){
            
        }
    }
}
``` 

The second attack scenario is a griefing attack. The paradigm of using a queue where items are strictly processed after their ordering and where users might call `processExits()` for exiting UTXOs that they have not initiated, is by design susceptible to this type of attack. The problem can only be mitigated by limiting the amount of gas that is provided to a call. There will be proportional griefing attack possible where a malicious user starts a large number of exits and pays X amount in fees and "good users" are interested in getting their exists processed and they have to pay the Y amount in processing fees to get to process their exits. Malicious users can use gas siphoning attacks to balance the spent fee ratio more in their favor. 

## Suggested Fix

I propose to set the fees for all external calls to untrusted addresses as low as possible. We probably want to provide enough so that a fallback function can process it and emit an event.We also need to consider the call `SafeERC20`. 

We should make the gas stipend update-able so that we can respond to changing gas prices in the future. Let's consider a similar mechanism than we have for `updateBondSize`. Up for discussion. 

As for the griefing attack I don't see how we can fix that with the current design. I think a malicious user needs proportionally more gas than a 'good user' but I want to look more into the economics.

**Comment by boolafish** [comment]
ref, one previous similar issue: https://github.com/omisego/plasma-contracts/issues/361

**Comment by thec00n** [comment]
hey @boolafish sorry #361 drop from my radar. Let's discuss this soon.

**Comment by pgebal** [comment]
@thec00n @paulperegud  It is intended that in scenario 1 processing fails. Most probably token is broken. As exits are queued per (vault_id, token) pair it blocks only exits for that particular token. I think we don't have to do anything to do in that scenario. If users are playing with broken tokens - be it.

**Comment by pdobacz** [comment]
Hey @thec00n, in scenario 1, `callee.call.value(0)("");` would return with a failure value, and the rest of the queue is able to continue, correct? Then isn't it possible to limit the gas stipend in that `call`, like `callee.call.value(0).gas(some_reasonable_stipend)("");`, so that it cannot drain the entire gas allowance of a tx?

I think someone set out to double-check if this behaves that way, was it you @pgebal ?

**Comment by thec00n** [comment]
@pgebal I see what you mean in the scenario that an attacker can spam his own exit queue and that this would stay isolated from the other queues. We still need to be careful in a scenario where the operator takes on the role of calling `processExits` for users because it might be cumbersome to look which ones are valid and which ones are not. 

Let's take the ETH process exit scenario. Here we have 2 calls that can be controlled by a malicious user: the address where the bond is sent to and the actual withdrawal address. So at both calls the attacker can drain 63/64 of all the gas and then there are still some expensive instructions after that. I think this could jam the exit queue permanently even if you send a lot of gas. Have not test it yet. At the very least this is very expensive for the one calling processExits() to even being able to process one item in the queue.  

https://github.com/omisego/plasma-contracts/blob/bab16aee4e799af9bbbf06d3ad97df701f91c273/plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessStandardExit.sol#L58-L67

https://github.com/omisego/plasma-contracts/blob/bab16aee4e799af9bbbf06d3ad97df701f91c273/plasma_framework/contracts/src/vaults/EthVault.sol#L46-L55

**Comment by pdobacz** [comment]
@thec00n 

aaah, ok. I didn't catch that (you wrote "fees", but I suppose "gas stipend" was meant).

On the updateable part, maybe let's not overdo it? The respective `call`s are only in `ExitGame` and `Vault` extensions (correct me if I'm wrong), so the stipend is not set in stone. We can just go with an educated guess I suppose

**Comment by thec00n** [comment]
I am not sure if we would overdo it by making it update-able but it's worth considering. Setting the gas stipend as low as possible has the advantage that griefing attacks are less effective and they would be an additional measure to prevent reentrancy. A low gas stipend might also affect users though that want to exit to a smart contract and they want to have more logic in the fallback function. I am not sure if that are all of the scenarios that are relevant ... maybe another reason why making the gas price updateable is worth considering.

**Comment by pdobacz** [comment]
Yeah, we can also extend (:joy:) our contract with a new Vault that has this either bumped or made update-able. By not overdoing I meant that we don't have to make update-able now, we can postpone till it proves to be needed ("if you want to exit to contracts, you need to use ETHVault2 etc")

**Comment by thec00n** [comment]
I thought about it again and I am ok if we stick to a static gas stipend. We need to warn users though and put up a big fat warning up that if they exit ETH or send a bond to a smart contract then they have to ensure that they create a fallback function that leaves enough buffer and it stays way under the gas stipend that we pass a long. 

As for the implementation I would suggest that we set the gas stipend with the constructor for all of the `call`s that we are using.  We have then more time to investigate what that value is going to be https://github.com/omisego/plasma-contracts/issues/386.

**Comment by thec00n** [comment]
@pdobacz wondering how this is coming along?

**Comment by boolafish** [comment]
Is the proposal here to use call() + gas(gas_stipend) for all Vaults and whenever sending out bond?

One question/discussion here, if we move toward to check whether external call is successful or not + we limit the gas, is there any reason we isolate the queue? It seems to me that that we don't gain anything more from that isolation?

**Comment by boolafish** [comment]
I want to discuss and clarify whether there is need to do the same for ERC20. An standard ERC20 contract, if I understand it correctly, should not call any external contract/address. As a result, when we are doing transfer, we would only call that ERC20 contract and the call would end there. It would not reach external contract if the ERC20 contract is a standard one. As a result, it seems to me this is still covered by the exit queue isolation protection.

However, if not, want to also discuss is there a better way to do this than copy the [SafeERC20 library](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/SafeERC20.sol) and add the gas stipend into it?

**Comment by thec00n** [comment]
In terms of the ERC20 transfers ` ...  It seems to me this is still covered by the exit queue isolation protection.` @boolafish I came to the same conclusion. I still wanted to think about it some more and also get some feedback from the auditors.

**Comment by boolafish** [comment]
Okay, I will pause the ERC20 part and fix the ETH transfer only as I don't have simple solution in my mind to fix ERC20 anyway....
