### ISSUE TITLE
Type agnostic input pointer behavior for spent flagging&double-spend detection

### ISSUE THREAD

**Issue by pdobacz** [omisego/plasma-contracts#387]
## Issue Type 

`design discussion`

## Description

This is a proposition of an improvement to the design and abstractions used in `ExitGame`. Discussed during the workshop with @kevsul @boolafish @pik694 (cc/ @paulperegud).

It could potentially simplify to have `bytes32` bitwise-comparison drive both:
  1. output flagging as spent
  2. double spend detection

Then the only place where you're concerned about the contents and semantics of the input pointer (the `bytes32`) is when you're starting standard exits. You then "remember" the input pointer type. Anyone that signs a tx spending that input pointer type is a double spend to challenge with.
:point_up:  that's type agnostic input pointer type

Right now we're calculating the `outputId` to do "flagging" part 1., whereas we're using `utxoPos` as "double spend detection" part. 2. This looks like complexity that can be avoided.

We don't have time to refactor this into an input pointer type agnostic behavior to just compare `bytes32` bitwise in both 1. and 2.

It seems like we can upgrade to it though, because the calculation of the "output flagging as spent" `bytes32` is up to the `ExitGame`.

-------

This has been spotted during the discussion the addition of tx inputs into the input challenging APIs (SE challenges, IFE canonicity challenges, IFE input challenges). IIRC, doing this modification could also relieve us of the necessity to deliver those additional inputs.

**Comment by boolafish** [comment]
just leaving some thoughts here:

For next round when we have some breaking changes that need an re-write/refactor to existing ExitGame contract, I think we should evaluate do we still want multiple input pointer type?:
1. If no, things would be simpler as it would be just `outputId`. Then the only refactor is we can compare the `outputId` (or whatever single id schema we decide to keep) with input.
1. If yes, assuming 1 output type <> 1 input pointer type, we can do the above. We add some complexity on `startXXExit` part as it needs to dispatch by output type to decide what schema it should be using. However, we would store the id according to input type to storage after it starts. (replacing our current `outputId` in storage).


One caveat is that currently we rely on `WireTransaction.sol`  to do that for arbitrary transaction. This means we embed some data (structure) dependency into code. Hopefully we might come up with some cleaner design that decouples the dependency but keeps the abstraction and flexibility.

**Comment by boolafish** [comment]
Closing this as I think there is no action item on this further more. We use this issue to note our discussion down. If there is any, feel free to re-open.
