### ISSUE TITLE
Current test coverage is not 100%

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#389]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior
The following contracts do not have yet a 100% test coverage:

- [x] RLPReader: currently tracked in #376: 
- [x] PriorityQueue: https://coveralls.io/builds/26522392/source?filename=contracts/src/framework/utils/PriorityQueue.sol
- [x] ExitGameController: I think we should replace the require with asserts as in both cases this should never occur. Security tools can then try to trigger the assert. 
(https://coveralls.io/builds/26522392/source?filename=contracts/src/framework/ExitGameController.sol#L54 and https://coveralls.io/builds/26522392/source?filename=contracts/src/framework/ExitGameController.sol#L73)
- [x] PaymentChallengeIFENotCanonical.sol: https://coveralls.io/builds/26522392/source?filename=contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol
- [x] PaymentChallengeIFEInputSpent: https://coveralls.io/builds/26522392/source?filename=contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol
- [x] PaymentChallengeStandardExit: https://coveralls.io/builds/26522392/source?filename=contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol
- [x] PaymentStartInFlightExit: https://coveralls.io/builds/26522392/source?filename=contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol
- [x] PaymentExitGame: https://coveralls.io/builds/26522392/source?filename=contracts/src/exits/payment/PaymentExitGame.sol
- [x] PaymentInFlightExitModelUtils: https://coveralls.io/builds/26522392/source?filename=contracts/src/exits/payment/PaymentInFlightExitModelUtils.sol

## Suggested Fix

- In a lot of cases the gaps in coverage are due to not triggering the negative branch of a require statement. Review the test suite and the existing code base and check if the require conditions are extensive enough and that the tests trigger the all code branches as expected. 
- Consider adding more negative test cases

**Comment by pgebal** [comment]
I think we can split that into a couple of PRs, so I put a checklist into issue description. I'm on it, currently working on ExitGameController and PaymentChallengeIFENotCanonical. The rest is up for grabs.

**Comment by boolafish** [comment]
I will take the Priority Queue test

**Comment by pgebal** [comment]
Starting with PaymentInFlightExitModelUtils and PaymentChallengeStandardExit.

**Comment by pgebal** [comment]
Starting with PaymentExitGame.

**Comment by pgebal** [comment]
Starting with `PaymentChallengeIFEInputSpent`.

**Comment by pgebal** [comment]
Starting with `PaymentStartInFlightExit`.

**Comment by boolafish** [comment]
I think this is done, currently 99%
