### ISSUE TITLE
PriorityQueue.delMin() assert violation

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#391]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior

An assert violation can be trigged if a new `PriorityQueue` is created and then `delMin` is called twice. The queue is assumes that there is always an item at index 1. This triggers an assert violation when accessing `queue.heapList[1]`.

https://github.com/omisego/plasma-contracts/blob/bab16aee4e799af9bbbf06d3ad97df701f91c273/plasma_framework/contracts/src/framework/utils/PriorityQueue.sol#L60

## Fix 

Check the length of the queue before accessing the smallest element of the list.

**Comment by pgebal** [comment]
@thec00n this is intended. `delMin` and `getMin` fail when queue it to short. We use `PriorityQueue` only for extracting the next exit to process. If there are none, transaction fails and that's ok. Do you think we should handle it gracefully or revert with more explicit error message? I think it's ok the way it is now. One thing that could be improved is to add a unit test that verifies if `delMin` fails with specific error message when queue it to short.

**Comment by thec00n** [comment]
`Do you think we should handle it gracefully or revert with more explicit error message`
yes
