### ISSUE TITLE
Unused variable in EthVault

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#392]
## Issue Type 

```
[ x ] bug report
[ ] feature request
```

## Current Behavior
The local variable is `withdrawEntryCounter` is not used.

https://github.com/omisego/plasma-contracts/blob/bab16aee4e799af9bbbf06d3ad97df701f91c273/plasma_framework/contracts/src/vaults/EthVault.sol#L8

## Suggested Fix
Remove it.

**Comment by kevsul** [comment]
Wonder why the solidity linter doesn't catch this? 😞
