### ISSUE TITLE
Maintainer can bypass exit game and vault quarantine periods by submitting not-yet-deployed contracts

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#410]
## Issue Type 

```
[x] bug report
[ ] feature request
```

#### Recommendation

`registerExitGame` should check that `extcodesize` of the submitted contract is non-zero.

## Current Behavior

The plasma framework uses an `ExitGameRegistry` to allow the maintainer to add new exit games after deployment. An exit game is any arbitrary contract. In order to prevent the maintainer from adding malicious exit games that steal user funds, the framework uses a "quarantine" system whereby newly-registered exit games have restricted permissions until their quarantine period has expired. The quarantine period is by default `3 * minExitPeriod`, and is intended to facilitate auditing of the new exit game's functionality by the plasma users. 

By registering an exit game at a contract which has not yet been deployed, the maintainer can prevent plasma users from auditing the game until the quarantine period has expired. After the quarantine period has expired, the maintainer can deploy the malicious exit game and immediately steal funds.

## Expected Behavior

The safety of the registry quarantine system relies heavily on users to monitor the current pending vault and exit game registrations to ensure the maintainer does not add malicious extensions to the plasma framework. It must be assumed that users notice and examine each addition to the plasma framework's registered extensions. The registry quarantine system should promote these efforts when possible by rejecting extensions with 0 codesize. It may also be prudent to lock the code hash of registered contracts.

## Steps to Reproduce

Exit games are registered in the following function, callable only by the plasma contract maintainer:

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol#L58-L78

Notably, the function does not check the `extcodesize` of the submitted contract. As such, the maintainer can submit the address of a contract which does not yet exist and is not auditable.

After at least `3 * minExitPeriod` seconds pass, the submitted contract now has full permissions as a registered exit game and can pass all checks using the `onlyFromNonQuarantinedExitGame` modifier:

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol#L33-L40

Additionally, the submitted contract passes checks made by external contracts using the `isExitGameSafeToUse` function:

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol#L48-L56

These permissions allow a registered quarantine to:

1. Withdraw any users' tokens from `ERC20Vault`:

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/vaults/Erc20Vault.sol#L52

2. Withdraw any users' ETH from `EthVault`:

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/vaults/EthVault.sol#L44

3. Activate and deactivate the `ExitGameController` reentrancy mutex:

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/framework/ExitGameController.sol#L58-L75

4. `enqueue` arbitrary exits:

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/framework/ExitGameController.sol#L115-L126

5. Flag outputs as "spent":

https://github.com/omisego/plasma-contracts/blob/b6fd6e8e70ca88bc26f7a1f55ba0cb3057bc8c52/plasma_framework/contracts/src/framework/ExitGameController.sol#L199-L204

## Suggested Fix

`registerExitGame` and `registerVault` should check that `extcodesize` is nonzero before beginning the quarantine period.

**Comment by thec00n** [comment]
@boolafish maybe something like this:

```
    function verifyContractCode(address newContract, bytes32 proposedHash) public returns (bool) {
        bytes32 actualHash;
        assembly {
             actualHash := extcodehash(newContract)
        
        }
        
        require (proposedHash == actualHash, "Hash of the contract provided does not match the proposed hash");
    }
```

**Comment by pdobacz** [comment]
If I may chime in, if this `extcodehash` mechanism doesn't fundamentally improve the security mechanism, I'd vote for not having it and avoiding this little addition of complexity (and risk: what if there's a bug in this code, preventing an honest maintainer from extending the contract?).

The security mechanism is that the Watcher should do:

```
if new contract registered and not audited successfully by me:
  mass_exit()
```

and the audit concerns a particular deployment, not just the bytecode.

Also note, that the registered contract might have non-zero bytecode and pass the hash-test, but still invite the possibility of being extended maliciously (e.g. it has some pluggable functionality). I think inducing a sense of false security should be avoided.

OTOH, I have no reservations towards a sanity check for maintainer's sake, a simple one: `bytecode != 0x`.

**Comment by thec00n** [comment]
Yeah I am with @pdobacz on this because of not adding more complexity to the system. Using a `!= 0x` is fine.

**Comment by wadeAlexC** [comment]
I agree that the watcher should be checking the main chain. 

I also think that `extcodesize != 0` should be checked for - while deployed contracts may have upgradable / extendable functionality, `extcodesize` seems like a reasonable sanity check that covers more cases than `!= 0x`. Locking `extcodehash` is probably not necessary.
