### ISSUE TITLE
ECDSA error value is not handled

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#454]
## Issue Type 

```
[X] bug report
[ ] feature request
```

## Current Behavior

The OpenZeppelin `ECDSA` library returns `address(0x00)` for many cases with malformed signatures:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/49042f2b1ae76eb9befa12000b98211981a139ec/contracts/cryptography/ECDSA.sol#L57-L63

The `PaymentOutputToPaymentTxCondition` contract does not explicitly handle this case:

https://github.com/omisego/plasma-contracts/blob/1c7cd867b1353ae72c825a6d15b2d382689f30ad/plasma_framework/contracts/src/exits/payment/spendingConditions/PaymentOutputToPaymentTxCondition.sol#L65-L68

## Suggested Fix

Adding a check to handle this case will make it easier to reason about the code.

**Comment by pdobacz** [comment]
Nice, I was quite sure we did check it, but that was the old contracts :) https://github.com/omisego/plasma-contracts/blob/v0.2/contracts/ECRecovery.sol#L51.

Curious however, there seems to have existed a test covering this, added here: https://github.com/omisego/plasma-contracts/commit/425eec8724d31cc8d50c75ceeeb0556027a99dcc

Did it not go red, when firing it against the new contracts? @pik694

**Comment by pik694** [comment]
It did not due some other checks:
https://github.com/omisego/plasma-contracts/blob/1c7cd867b1353ae72c825a6d15b2d382689f30ad/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L106

**Comment by pdobacz** [comment]
oh, whoops, then it's the test that needs fixing.
