### ISSUE TITLE
Recommendation: Remove `WireTransaction` and `PaymentOutputModel`. Fold functionality into an extended `PaymentTransactionModel`

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#456]
## Issue Type 

```
[ ] bug report
[X] feature request
```

#### Description

RLP decoding is performed on transaction bytes in each of `WireTransaction`, `PaymentOutputModel`, and `PaymentTransactionModel`. The latter is the primary decoding function for transactions, while the former two contracts deal with outputs specifically. 

Both `WireTransaction` and `PaymentOutputModel` make use of `RLPReader` to decode transaction objects, and both implement very similar features. Rather than having a codebase with two separate definitions for `struct Output`, `PaymentTransactionModel` should be extended to implement all required functionality.

#### Examples

* `PaymentTransactionModel` should include three distinct decoding functions:
    * `decodeDepositTx` decodes a deposit transaction, which has no inputs and exactly 1 output.
    * `decodeSpendTx` decodes a spend transaction, which has exactly 4 inputs and 4 outputs. 
    * `decodeOutput` decodes an output, which is a long list with 4 fields (`uint`, `address`, `address`, `uint`)

A mock implementation including `decodeSpendTx` and `decodeOutput` is shown here: https://gist.github.com/wadeAlexC/7820c0cd82fd5fdc11a0ad58a84165ae

OmiseGo may want to consider enforcing restrictions on the ordering of empty and nonempty fields here as well.

**Comment by kevsul** [comment]
Resolved in #502
