### ISSUE TITLE
Recommendation: Remove optional arguments and clean unused code

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#457]
## Issue Type 

```
[ ] bug report
[X] feature request
```

#### Description

Several locations in the codebase feature unused arguments, functions, return values, and more. There are two primary reasons to remove these artifacts from the codebase:

1. Mass exits are the primary safeguard against a byzantine operator. The biggest bottleneck of a mass exit is transaction throughput, so plasma rootchain implementations should strive to be as efficient as possible. Many unused features require external calls, memory allocation, unneeded calculation, and more.

2. The contracts are set up to be extensible by way of the addition of new exit games to the system. "Optional" or unimplemented features in current exit games should be removed for simplicity's sake, as they currently make up a large portion of the codebase.

#### Examples

* Output guard handlers
  * These offer very little utility in the current contracts. The main contract, `PaymentOutputGuardHandler`, has three functions:
      * `isValid` enforces that some "preimage" value passed in via calldata has a length of zero. This could be removed along with the unused "preimage" parameter.
      * `getExitTarget` converts a `bytes20` to `address payable` (with the help of `AddressPayable.sol`). This could be removed in favor of using `AddressPayable` directly where needed.
      * `getConfirmSigAddress` simply returns an empty address. This should be removed wherever used - empty fields should be a rare exception or an error, rather than being injected as unused values into critical functions.
  * The minimal utility offered comes at the price of using an external call to the `OutputGuardHandlerRegistry`, as well as an external call for each of the functions mentioned above. Overall, the existence of output guard handlers adds thousands of gas to the exit process.
  * Referenced contracts: `IOutputGuardHandler`, `OutputGuardModel`, `PaymentOutputGuardHandler`, `OutputGuardHandlerRegistry`

* Payment router arguments
  * Several fields in the exit router structs are marked "optional," and are not used in the contracts. While this is not particularly impactful, it does clutter and confuse the contracts. Many "optional" fields are referenced and passed into functions which do not use them. Of note is the crucially-important signature verification function, `PaymentOutputToPaymentTxCondition.verify`, where `StartExitData.inputSpendingConditionOptionalArgs` resolves to an unnamed parameter:

https://github.com/omisego/plasma-contracts/blob/8f4c47025ef591334df24d25b2524df38669a4d0/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L323-L332

https://github.com/omisego/plasma-contracts/blob/8f4c47025ef591334df24d25b2524df38669a4d0/plasma_framework/contracts/src/exits/payment/spendingConditions/PaymentOutputToPaymentTxCondition.sol#L40-L48

The additional fields clutter the namespace of each struct, confusing the purpose of the other fields. For example, `PaymentInFlightExitRouterArgs.StartExitArgs` features two fields, `inputTxsConfirmSigs` and `inFlightTxsWitnesses`, the former of which is marked "optional". In fact, the `inFlightTxsWitnesses` field ends up containing the signatures passed to the spending condition verifier and `ECDSA` library: 

https://github.com/omisego/plasma-contracts/blob/8f4c47025ef591334df24d25b2524df38669a4d0/plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouterArgs.sol#L4-L24

**Comment by boolafish** [comment]
handled in PR: #496 and #503
