### ISSUE TITLE
List of minor findings

### ISSUE THREAD

**Issue by kbak** [omisego/plasma-contracts#462]
```
[X] bug report
[ ] feature request
```
### Enforce ownership renouncement
**Contract(s) affected:** `OutputGuardHandlerRegistry.sol`, `SpendingConditionRegistry.sol`

**Severity:** Low

**Description:** Both `OutputGuardHandlerRegistry` and `SpendingConditionRegistry` are expected to have their ownership renounced before injecting the registries to the `ExitGame` contracts. Although stated in the documentation, this requirement is not enforced programmatically. Hence, there is nothing requiring the owner to actually renounce the ownership. As such, the owner could register new output guard handlers and spending conditions to perform malicious operations on the Plasma chain.

**Recommendation:** We recommend enforcing the ownership renouncement programmatically. For example, the vaults may reject any deposits as long as `OutputGuardHandlerRegistry` and `SpendingConditionRegistry` have owners.

### Maintainer may register a malicious game
**Contract(s) affected:** `ExitGameRegistry.sol`

**Severity:** Undetermined

**Description:** Maintainer has the privilege of adding new exit games. Each new exit game is quarantined for three exit periods -- that's the period in which the community of Plasma chain users may audit the newly added exit game. In case they realize that the game is malicious, they may decide to exit the chain. Given that it may take two exit periods to perform an exit, is it realistic that the community discovers a problematic exit game within a single exit period?

**Recommendation:** Currently we have no recommendation.

## Adherence to Specification

The functions `EthDepositVerifier.verify()`, `Erc20DepositVerifier.verify()`, and `PaymentOutputModel.decode()` don't check `decodedTx.outputs[0].outputType`. Should they?

## Adherence to Best Practices

Although the code uses the experimental feature `ABIEncoderV2`, overall, it conforms to best practices and it makes good use of modularization. We provide further ideas for improvements below:
* in `FailFastReentrancyGuard.sol` there is no need to import `PlasmaFramework.sol`. We recommend importing `ExitGameController.sol` instead.
* in `Erc20DepositVerifier.sol#46` there is a strict equality requiring user to approve an exact amount of tokens. Such a design prohibits the user from making a single approval for multiple deposits. To facilitate flexibility and to reduce gas usage, we recommend using `>=` instead of equality. Furthermore, the comment in line `Erc20Vault.sol#32` would hint on the recommended approach.
* in `PaymentInFlightExitModelUtils.isFirstPiggybackOfTheToken()` there is an unused variable `isPiggybackInput` which is write-only. We recommend removing it.
* in `WireTransaction.sol` following the line 32, we recommend checking the length of `output`, e.g.,  `require(4 == output.length, "Invalid output encoding")`.
* in `VaultRegistry.sol` the function `registerVault()` takes `uint256 _vaultId` as an argument. We recommend simplifying the code by introducing a unique internal counter that could then be used to generate `_vaultId` and return it from the function.
* `utxoPos` has inconsistent definitions; for example, it is defined as `uint192` in `PaymentExitDataModel.StandardExit` and `PaymentStandardExitRouterArgs.StartStandardExitArgs`, whereas it is defined as `uint256` in `ExitChallenged.PaymentStandardExitRouter` and `UtxoPosLib.UtxoPos`.
* similarly, `exitId` is defined as `uint160` in `ExitId.getStandardExitId()`, whereas is it defined as `uint192` in `PaymentExitDataModel.StandardExitMap`.
* unlocked pragma in `RLPReader.sol`. Since it's a clone-and-owned library, we recommend locking pragma as in other contracts.
* unlocked pragma in `TxFinalizationModel.sol` We recommend locking the pragma.
* since the max number of outputs and inputs associated with a UTXO is 4, the data type for indices could be `uint8` instead of `uint16` (e.g., the return value of `UtxoPosLib.outputIndex()`, or input of `PaymentOutputToPaymentTxCondition.verify()`).
* it is unclear why the function `PaymentExitGame.processExit()` takes a second unnamed argument (presumably vault Id). If it is not used, we recommend removing it.
* it is unclear why `OutputId.computeDepositOutputId()`takes `_outputIndex` as an argument. If deposit's output UTXO is always zero, we recommend removing it.
* in `PaymentInFlightExitModelUtils.sol`, it is unclear why there are both `clearOutputPiggyback()` and `clearOutputPiggybacked()`. The former appears wrong since it does not shift the `index`. However, is not used anywhere in the code base; we recommend removing it.
* typos: in `EthVault.sol`: "unucessful"  -> "unsuccessful", and `ExitId.sol`: "depost" -> "deposit".
* constants `MAX_INPUT_NUM` and `MAX_OUTPUT_NUM` are re-defined in multiple different places (e.g., `PaymentInFlightExitModelUtils.sol`, `PaymentExitDataModel.sol`, `PaymentPiggybackInFlightExit.sol`, `PaymentTransactionModel.sol`, `PaymentEip712Lib.sol`). We recommend extracting them to some shared  contract/library.
* the field `EthVault.withdrawEntryCounter` is not used anywhere in the code. We recommend removing it.
* in `PaymentOutputModel.sol#28` and `PaymentOutputGuardHandler.sol#15`, the statement `AddressPayable.convert()` appears to be redundant.
* in `PaymentStandardExitRouter.sol`the events `Exit*` on lines 49-64 are redefined by the corresponding controller libraries, and these local definitions do not appear to be used.  Similar comment applies to `PaymentStandardExitRouter.sol` and events from lines 58-106. We recommend removing the redundant events.
* in `PaymentStandardExitRouterArgs.sol#8`, there is the comment `outputGuardPreimage (Optional) Output guard preimage data`, however, `PaymentOutputGuardHandler.isValid()` seems to suggest that this field must have length 0. The field does not appear to be "optional", but rather "disallowed".

**Comment by boolafish** [comment]
> in PaymentStandardExitRouter.solthe events Exit* on lines 49-64 are redefined by the corresponding controller libraries, and these local definitions do not appear to be used. Similar comment applies to PaymentStandardExitRouter.sol and events from lines 58-106. We recommend removing the redundant events.

We did this for this reason: https://ethereum.stackexchange.com/questions/11137/watching-events-defined-in-libraries

I think the last time I check I was not able to filter with `pastEvents` using web3. Though it is possible for clients not relying on abi to get the event out. Not sure is there better solution then duplicate the event declaration though? @kbak do you have any input on this one?

**Comment by kbak** [comment]
I see. We didn't know about this limitation, so don't really have a better proposal. Please disregard it and thanks for the explanation.
