### ISSUE TITLE
Recommendation: Implement additional existence and range checks on inputs and storage reads

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#463]
#### Description

Many input validation and storage read checks are made implicitly, rather than explicitly. The following compilation notes each line of code in the exit controller contracts where an additional check should be added.

##### 1. `PaymentChallengeIFEInputSpent`:

* Check that `inFlightTx` has a nonzero input at the provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L96

* Check that each transaction is nonzero and is correctly formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L98-L101

* Check that resulting `outputId` is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L123

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L125

* See #466:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L126

* Check that `inputTx` is nonzero and well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L127-L128

* Check that output is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L149

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L156

* Check that `challengingTx` has a nonzero input at provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol#L163

##### 2. `PaymentChallengeIFENotCanonical`:

* Check that each transaction is nonzero and is correctly formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L98-L101

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L104

* See #466:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L107

* Check that `inputTx` is nonzero and well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L108-L110

* Check that `inFlightTx` has a nonzero input at the provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L112-L113

* Check that output is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L115

* Check that `competingTx` has a nonzero input at provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L126

* Check that resulting position is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L133

* Check that `inFlightTxPos` is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L171-L173

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L175

* Check that block root is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L176

* Check that `inFlightTx` is nonzero and well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L178

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L218

##### 3. `PaymentChallengeIFEOutputSpent`:

* Check that `inFlightTx` is nonzero and is well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L54

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L58

* Check that `inFlightTx` has a nonzero output at the provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L60-L63

* Check that bond size is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L70

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L83

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L101

* Check that `challengingTx` is nonzero and is well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L102

* Check that output is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L103

* Check that `challengingTx` has a nonzero input at provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L116

##### 4. `PaymentChallengeStandardExit`:

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L110

* Check that `exitingTx` is nonzero and well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L112

* Check that output is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L111-L113

* Check that `challengeTx` is nonzero and well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L128

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L134

* See #466:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L157

* Check that `challengeTx` has a nonzero input at provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol#L166

##### 5. `PaymentPiggybackInFlightExit`:

* Check that `inFlightTx` is nonzero and well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol#L93

* Check that `inFlightTx` has a nonzero input at provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol#L99

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol#L108

* Check that `inFlightTx` is nonzero and is well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol#L130

* Check that `inFlightTx` has a nonzero output at provided index:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol#L136

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol#L147

##### 6. `PaymentStartInFlightExit`:

* Check that `inFlightTx` is nonzero and is well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L146

* Check that the length of `inputTxs` is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L150

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L167

* See #466:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L180

* Check that each `inputTxs` is nonzero and well-formed:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L181-L183

* Check that each output is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L200

* Check that `inFlightTx` has nonzero inputs for all `i`:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L327-L328

* Check that each output is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L407

##### 7. `PaymentStartStandardExit`:

* See #465:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol#L119

* Check that output is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol#L121

* Check that timestamp is nonzero:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol#L124

**Comment by pgebal** [comment]
@kevsul 
1.1 No need for that check, if it's not piggybacked require will fail, if it's piggybacked it's non zero.
1.2 It's checked when transaction is decoded.
1.3 Checked a couple lines below, when comparing with `challengingTxInputOutputId`
1.4 Already solved
1.5 Already solved
1.6 It's checked when transaction is decoded.
1.7 Already solved
1.8 Checked when decoding output

2.1 It's checked later in `MoreVpFinalization.isPrtocolFinalized` call
2.2 Already solved
2.3 Already solved
2.4 Checked when decoding input tx.
2.5 Not checked.
2.6 Checked when decoding.
2.7 Should be handled by a spending condition.
2.8 It can be zero. Competing transaction might not be included in Plasma block.
2.9 Added the check
2.10 Already solved
2.11 Already solved
2.12 Not done
2.13 Already solved

3.1 Checked when decoding
3.2 Already solved
3.3 No need for that check, if it's not piggybacked require will fail, if it's piggybacked it's non zero.
3.4 It's taken care off when doing the piggyback.
3.5 Already solved
3.6 Already solved
3.7 Checked when decoding
3.8 Checked when decoding
3.9 Should be handled by a spending condition

4.1 Already solved
4.2 Cheked when decoding
4.3 Added the check to verify is outputIndex is not out of bounds
4.4 Checked when decoding
4.5 Already solved
4.6 Already solved
4.7 Should be handled in spending condition

5.1 Not needed. If it's zero bytes, then check of `exitStartTimestamp` would fail.
5.2 That's handled, when starting in-flight exit (`setInFlightExitInputs`)
5.3 Already solved
5.4 Not needed. If it's zero bytes, then check of `exitStartTimestamp` would fail.
5.5 That's handled, when starting in-flight exit (`setInFlightExitOutputs`)
5.6 Already solved

6.1 Checked when decoding
6.2 Added the check
6.3 Already solved
6.4 Already solved
6.5 Checked when decoding
6.6 Checked when decoding
6.7 Checked when decoding in `setInFlightExitInputs`
6.8 checked when decoding

7.1 Already solved
7.2 Checked when decoding
7.3 Added the check

**Comment by kevsul** [comment]
Great @pgebal 😄
