### ISSUE TITLE
Recommendation: Merge `TxPosLib` into `UtxoPosLib` and implement a `decode` function with range checks

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#465]
## Issue Type 

```
[ ] bug report
[X] feature request
```

#### Description

`TxPosLib` and `UtxoPosLib` serve very similar functions. They both provide utility functions to access the block number and tx index of a packed utxo position variable. `UtxoPosLib`, additionally, provides a function to retrieve the output index of a packed utxo position variable.

What they both lack, though, is sanity checks on the values packed inside a utxo position variable. By implementing a function `UtxoPosLib.decode(uint _utxoPos) returns (UtxoPos)`, each exit controller contract can ensure that the values it is using make logical sense. The `decode` function should check that:

* `txIndex` is between 0 and the maximum number of transactions per block
* `outputIndex` is between 0 and 3

Currently, neither of these restrictions is explicitly enforced. As for `blockNum`, the best check is that it exists in the `PlasmaFramework` contract with a nonzero root. Since `UtxoPosLib` is a pure library, that check is better performed elsewhere (See #465).

Once implemented, all contracts should avoid casting values directly to the `UtxoPos` struct, in favor of using the `decode` function. Merging the two files will help with this.

**Comment by pdobacz** [comment]
Thank you! I wonder, whether this is related to https://github.com/omisego/plasma-contracts/issues/254 ?

**Comment by wadeAlexC** [comment]
I can't quite understand the original comment, but I think they're semi-related.

**Comment by pgebal** [comment]
The thing is we do not have a limitation on `outputIndex` and `txIndex` values on contract other than `outputIndex` is less than `10000` and 'txIndex' is less than `100000`
The way we have coded it, every `uint256` can be directly casted to `UtxoPos` and `blockNum` and 'txIndex` and `outputIndex` functions return proper values.
