### ISSUE TITLE
Recommendation: Add a tree height limit check to `Merkle.sol`

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#467]
## Issue Type 

```
[ ] bug report
[X] feature request
```

#### Description

Each plasma block has a maximum of `2 ** 16` transactions, which corresponds to a maximum Merkle tree height of 16. The `Merkle` library currently checks that the proof is comprised of 32-byte segments, but neglects to check the maximum height:

https://github.com/omisego/plasma-contracts/blob/51cfbbae921b98f7439d94db6c3d58878d475fc3/plasma_framework/contracts/src/utils/Merkle.sol#L17-L23

**Comment by pgebal** [comment]
It would be very convenient to hard code that (that would also solve issue #452) but I think we do not want to hard code the size of the trees. Right now blocks are being produced with a maximum number of `2 ** 16` plasma transactions but if we decide to change that we would rather not update contracts

**Comment by wadeAlexC** [comment]
I agree that it would be harder to change (would probably require a new exit game), but I think you should view major upgrades to the plasma chain as part of a major upgrade to the smart contracts. The contracts should not be expected to handle different upgrades, especially if that's not planned yet.

**Comment by pgebal** [comment]
I believe this PR: https://github.com/omisego/plasma-contracts/pull/452 mitigates this issue. We are protected from preimage attacks, so I think we do not longer need to require height of the Merkle tree to be 16.
