### ISSUE TITLE
Recommendation: Remove `TxFinalizationModel` and `TxFinalizationVerifier`. Implement stronger checks in `Merkle`

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#471]
## Issue Type 

```
[ ] bug report
[X] feature request
```

#### Description

`TxFinalizationVerifier` is an abstraction around the block inclusion check needed for many of the features of plasma exit games. It uses a struct defined in `TxFinalizationModel` as inputs to its two functions: `isStandardFinalized` and `isProtocolFinalized`. 

`isStandardFinalized` returns the result of an inclusion proof. Although there are several branches, only the first is used:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/utils/TxFinalizationVerifier.sol#L19-L32

`isProtocolFinalized` is unused:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/utils/TxFinalizationVerifier.sol#L34-L47

The abstraction used introduces branching logic and requires several files to be visited to fully understand the function of each line of code: `ITxFinalizationVerifier`, `TxFinalizationModel`, `TxPosLib`, `Protocol`, `BlockController`, and `Merkle`. Additionally, the abstraction obfuscates the underlying inclusion proof primitive when used in the exit game contracts. `isStandardFinalized` is not clearly an inclusion proof, and `isProtocolFinalized` simply adds confusion.

Finally, the abstraction may have ramifications on the safety of `Merkle.sol`. As it stands now, `Merkle.checkMembership` should never be called directly by the exit game controllers, as it lacks an important check made in `TxFinalizationVerifier.checkInclusionProof`:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/utils/TxFinalizationVerifier.sol#L49-L59

By introducing the abstraction of `TxFinalizationVerifier`, the input validation performed by `Merkle` is split across multiple files, and the reasonable-seeming decision of calling `Merkle.checkMembership` directly becomes unsafe. In fact, this occurs in one location in the contracts:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L187-L204

#### Recommendation

1. Remove `TxFinalizationVerifier` and `TxFinalizationModel`

2. Implement a proof length check in `Merkle.sol`

3. Call `Merkle.checkMembership` directly from exit controller contracts:

* `PaymentChallengeIFEOutputSpent.verifyInFlightTransactionStandardFinalized`:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol#L91

* `PaymentChallengeIFENotCanonical.verifyCompetingTxFinalized`:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol#L244

* `PaymentStartInFlightExit.verifyInputTransactionIsStandardFinalized`:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol#L307-L308

4. If none of the above recommendations are implemented, ensure that `PaymentChallengeIFENotCanonical` uses the abstraction `TxFinalizationVerifier` so that a length check is performed on the inclusion proof.

**Comment by kevsul** [comment]
Tx finalization was refactored in #503
