### ISSUE TITLE
Recommendation: Remove `PaymentOutputToPaymentTxCondition` and `SpendingConditionRegistry`

### ISSUE THREAD

**Issue by wadeAlexC** [omisego/plasma-contracts#472]
## Issue Type 

```
[ ] bug report
[X] feature request
```

#### Description

`PaymentOutputToPaymentTxCondition` is an abstraction around the transaction signature check needed for many components of the exit games. Its only function, `verify`, returns `true` if one transaction (`inputTxBytes`) is spent by another transaction (`spendingTxBytes`):

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/exits/payment/spendingConditions/PaymentOutputToPaymentTxCondition.sol#L40-L69

##### Verification process

The verification process is relatively straightforward. The contract performs some basic input validation, checking that the input transaction's `txType` matches `supportInputTxType`, and that the spending transaction's `txType` matches `supportSpendingTxType`. These values are set during construction.

Next, `verify` checks that the spending transaction contains an input that matches the position of one of the input transaction's outputs. 

Finally, `verify` performs an EIP-712 hash on the spending transaction, and ensures it is signed by the owner of the output in question.

##### Implications of the abstraction

The abstraction used requires several files to be visited to fully understand the function of each line of code: `ISpendingCondition`, `PaymentEIP712Lib`, `UtxoPosLib`, `TxPosLib`, `PaymentTransactionModel`, `PaymentOutputModel`, `RLPReader`, `ECDSA`, and `SpendingConditionRegistry`. Additionally, the abstraction obfuscates the underlying spending condition verification primitive where used.

Finally, understanding the abstraction requires an understanding of how `SpendingConditionRegistry` is initialized, as well as the nature of its relationship with `PlasmaFramework` and `ExitGameRegistry`. The aforementioned `txType` values, `supportInputTxType` and `supportSpendingTxType`, are set during construction. Their use in `ExitGameRegistry` seems to suggest they are intended to represent different versions of transaction types, and that separate exit game contracts are meant to handle different transaction types:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol#L58-L78

##### Migration and initialization

The migration script seems to corroborate this interpretation:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/migrations/5_deploy_and_register_payment_exit_game.js#L109-L124

The migration script shown above deploys two different versions of `PaymentOutputToPaymentTxCondition`. The first sets `supportInputTxType` and `supportSpendingTxType` to `PAYMENT_OUTPUT_TYPE` and `PAYMENT_TX_TYPE`, respectively. The second sets those same variables to `PAYMENT_OUTPUT_TYPE` and `PAYMENT_V2_TX_TYPE`, respectively. 

The migration script then registers both of these contracts in `SpendingConditionRegistry`, and then calls `renounceOwnership`, freezing the spending conditions registered permanently:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/migrations/5_deploy_and_register_payment_exit_game.js#L126-L135

Finally, the migration script registers a single exit game contract in `PlasmaFramework`:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/migrations/5_deploy_and_register_payment_exit_game.js#L137-L143

Note that the associated `_txType` is permanently associated with the deployed exit game contract:

https://github.com/omisego/plasma-contracts/blob/493ddeadc821fae7293cfc3088939eddf89cb559/plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol#L58-L78

##### Conclusion

Crucially, this association is never used. It is implied heavily that transactions with some `txType` must use a certain registered exit game contract. In fact, this is not true. When using `PaymentExitGame`, its routers, and their associated controllers, the `txType` is invariably inferred from the encoded transaction, not from the mappings in `ExitGameRegistry`. If initialized as-is, both `PAYMENT_TX_TYPE` and `PAYMENT_V2_TX_TYPE` transactions may be exited using `PaymentExitGame`, provided they exist in the plasma chain.

#### Recommendation

* Remove `PaymentOutputToPaymentTxCondition` and `SpendingConditionRegistry` 

* Implement checks for specific spending conditions directly in exit game controllers. Emphasize clarity of function: ensure it is clear when called from the top level that a signature verification check and spending condition check are being performed.

* If the inferred relationship between `txType` and `PaymentExitGame` is correct, ensure that each `PaymentExitGame` router checks for its supported `txType`. Alternatively, the check could be made in `PaymentExitGame` itself.

**Comment by boolafish** [comment]
> Crucially, this association is never used. It is implied heavily that transactions with some txType must use a certain registered exit game contract. In fact, this is not true.

So tx type and exit game should be 1:1 mapping by design. Whenever that is not true, it should be consider a bug. A fix applied in #473

**Comment by boolafish** [comment]
So 1:1 relationship is handled. We've decided to keep spending condition registry abstraction as we do see value on it, especially we are trying to do fee as a second tx type already.

see more detail in #501.
