### ISSUE TITLE
migrate Mock contracts with devel flag

### ISSUE THREAD

**Issue by InoMurko** [omisego/plasma-contracts#509]
## Issue Type 

```
[ ] bug report
[ x] feature request
```

## Current Behavior
Currently `npx truffle migrate` only deploys essential (root chain) contracts.

## Expected Behavior
Because contracts are also used in development, we would like to have access to contracts in
`./plasma_framework/contracts/mocks/`, specifically `plasma-contracts/plasma_framework/contracts/mocks/transactions/eip712Libs/PaymentEip712LibMock.sol`.

## Suggested Fix
`npx truffle migrate --network remote command` should accept a `--devel` flag that deploys mock contract above as well, and expose them in outputs.json so that they're able to be served ... 

## Motivation for Change
Support development on elixir-omg side (this allows us to delete some of the helper code that used to do the deployment)

**Comment by InoMurko** [comment]
The currently identified contracts we would need are `PaymentEip712LibMock` and `ERC20Mintable` (openzeppelin_solidity)

**Comment by pdobacz** [comment]
slight suggestion to avoid using the word "mock" in this context (and rename the contracts that fall into this category). Would `proxy` work for the `PaymentEip712Lib...` thing? I think currently this is the only contract that does, but not sure.

**Comment by InoMurko** [comment]
I don't have an opinion on this. As long as it's evident it's not what we're shipping to production...

As per discussion on Slack,  `git SHA1 of length 7` should be stored in the contracts so relevant parties are able to retrieve that (similarly to how we retrieve `MIN_EXIT_PERIOD`)
