### ISSUE TITLE
Increase quarantine period of new exit games

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#512]
## Issue Type 

```
[ x  ] bug report
[ ] feature request
```

## Current Behavior
Currently if a new exit game is introduced that allows an operator to withdraw instantly all funds then users would not be guaranteed to exit safely within 2 weeks. This has been flagged in one of the audit findings here https://github.com/omisego/plasma-contracts/issues/462. There is also a previous discussion around the topic in this issue https://github.com/omisego/plasma-contracts/issues/197.

## Suggested Fix
I propose to increase the quarantine period to 4 times the exit period.

**Comment by kevsul** [comment]
Looks like a good idea. The discussion in #197 decided on 3 weeks though...

**Comment by kasima** [comment]
Synced up with @thec00n. For this first deployment, I want to bias towards safety, so `4 * minExitPeriod` is :+1:.

@Pongch – FYI and let me know if that's going to be a problem.
