### ISSUE TITLE
test examples for standard exits with standard exit id passed to processExits/4

### ISSUE THREAD

**Issue by InoMurko** [omisego/plasma-contracts#534]
As per integration doc: 
https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/docs/integration-docs/integration-doc.md#starting-an-in-flight-exit
and also
https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/docs/integration-docs/integration-doc.md#processing-a-standard-exit

processing a SE is able to receive a `topExitId` argument that one can get from 
```
data = ABI.encode("getStandardExitId(bool,bytes,uint256)", [true, exit_data.txbytes, exit_data.utxo_pos])
{:ok, result} = Ethereumex.HttpClient.eth_call(%{to: exit_game_contract_address, data: Encoding.to_hex(data)})
standard_exit_id =
      result
      |> Encoding.to_binary()
      |> ABI.TypeDecoder.decode([{:uint, 160}])
      |> hd()
``` 
and process the exit by passing the above standard_exit_id into process exits
```
data =
      ABI.encode(
        "processExits(uint256,address,uint160,uint256)",
        [Itest.Account.vault_id(Currency.ether()), Currency.ether(), standard_exit_id, 1]
      )
```

related data:
```
%Itest.StandardExitClient{
  add_exit_queue_hash: "0x37103332935522ccc026dc24988d6aa28371308889d5308797710e9aa0abc2d0",
  address: "0xb61a62aed0ec340ea9186f7d125466c6e31c5ff9",
  exit_data: %Itest.ApiModel.ExitData{
    proof: "0xf39a869f62e75cf5f0bf914688a6b289caf2049435d8e68c5c5e6d05e44913f34ed5c02d6d48c8932486c99d3ad999e5d8949dc3be3b3058cc2979690c3e3a621c792b14bf66f82af36f00f5fba7014fa0c1e2ff3c7c273bfe523c1acf67dc3f5fa080a686a5a0d05c3d4822fd54d632dc9cc04b1616046eba2ce499eb9af79f5eb949690a0404abf4cebafc7cfffa382191b7dd9e7df778581e6fb78efab35fd364c9d5dadad4569b6dd47f7feabafa3571f842434425548335ac6e690dd07168d8bc5b77979c1a6702334f529f5783f79e942fd2cd03f6e55ac2cf496e849fde9c446fab46a8d27db1e3100f275a777d385b44e3cbc045cabac9da36cae040ad516082324c96127cf29f4535eb5b7ebacfe2a1d6d3aab8ec0483d32079a859ff70f9215970a8beebb1c164c474e82438174c8eeb6fbc8cb4594b88c9448f1d40b09beaecac5b45db6e41434a122b695c5a85862d8eae40b3268f6f37e414337be38eba7ab5bbf303d01f4b7ae07fd73edc2f3be05e43948a34418a3272509c43c2811a821e5c982ba51874ac7dc9dd79a80cc2f05f6f664c9dbb2e454435137da06ce44de45532a56a3a7007a2d0c6b435f726f95104bfa6e707046fc154bae91898d03a1a0ac6f9b45e471646e2555ac79e3fe87eb1781e26f20500240c379274fe91096e60d1545a8045571fdab9b530d0d6e7e8746e78bf9f20f4e86f06",
    txbytes: "0xf85b01c0f6f501f394b61a62aed0ec340ea9186f7d125466c6e31c5ff9940000000000000000000000000000000000000000880de0b6b3a764000080a00000000000000000000000000000000000000000000000000000000000000000",
    utxo_pos: 2000000000
  },
  exit_game_contract_address: "0x92ce4d7773c57d96210c46a07b89acf725057f21",
  process_exit_receipt_hash: nil,
  standard_exit_bond_size: 14000000000000000,
  **standard_exit_id: 1373923369531234505036744913361103306032312024,**
  start_standard_exit_hash: "0xaad1c8d35baad1b6482dd6961a19eff818a3009066070d314355383204ee4e03",
  total_gas_used: nil,
  utxo: %Itest.ApiModel.Utxo{
    amount: 1000000000000000000,
    blknum: 2,
    currency: "0x0000000000000000000000000000000000000000",
    oindex: 0,
    owner: "0xb61a62aed0ec340ea9186f7d125466c6e31c5ff9",
    txindex: 0,
    utxo_pos: 2000000000
  }
}
```

```
calling processExits with arguments: 
[Itest.Account.vault_id(Currency.ether()), Currency.ether(), standard_exit_id, 1]
[
  1,
  <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>,
  1373923369531234505036744913361103306032312024,
  1
]

```

but this transaction immediately gets reverted:
```
{:ok, %{"blockHash" => "0xcd89bcc90cc23a5cde062f1691de085db9086f8601e8bcccc8a628899737fc90", "blockNumber" => "0x546", "contractAddress" => nil, "cumulativeGasUsed" => "0x8cf9", "from" => "0xb61a62aed0ec340ea9186f7d125466c6e31c5ff9", "gasUsed" => "0x8cf9", "logs" => [], "logsBloom" => "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000", "status" => "0x0", "to" => "0xc673e4ffcb8464faff908a6804fe0e635af0ea2f", "transactionHash" => "0x71f4f2953ca2b373cf0d4fe74ac15fb7a854b923ab2430830b9eb5a460b8e6f2", "transactionIndex" => "0x0"}}
```
The revert reason is: `Top exit ID of the queue is different to the one specified`
Which is odd, because this was run against a completely empty system (fresh geth + elixir-omg).

_Looking at the code repository, I couldn't find any test examples that would actually pass in the ID (they all pass in 0)._ Found python tests!
halp!

**Comment by boolafish** [comment]
are you starting an IFE or SE? startIFE would not enqueue until it is piggybacked.

> Looking at the code repository, I couldn't find any test examples that would actually pass in the ID 

The exitId is tested here:
https://github.com/omisego/plasma-contracts/blob/075c3782628e305794331f9ab2cbd1b032ccf823/plasma_framework/test/src/framework/ExitGameController.test.js#L331

Also, for debug and tracking purpose, client has access to the priority queue data, could follow the steps done in the following tests (`controller` is the `PlasmaFramework` from client's point of view):

https://github.com/omisego/plasma-contracts/blob/075c3782628e305794331f9ab2cbd1b032ccf823/plasma_framework/test/src/framework/ExitGameController.test.js#L217-L222

or

https://github.com/omisego/plasma-contracts/blob/075c3782628e305794331f9ab2cbd1b032ccf823/plasma_framework/test/src/framework/ExitGameController.test.js#L236-L237

**Comment by InoMurko** [comment]
> are you starting an IFE or SE? startIFE would not enqueue until it is piggybacked.

SE.

Cool, will implement the other stuff to see what's in the queue and report back.

**Comment by InoMurko** [comment]
This might be a bit harder to implement... because these "helper" functions you've mentioned @boolafish are not in the same exit game contract, correct? Is there a way for me to retrieve ExitGameController contract address on the fly (similarly to how I got exit_game_contract_address based on payment id type)?

**Comment by boolafish** [comment]
`ExitGameController` is the `PlasmaFramework`. So just do the helper functions to the `PlasmaFramework`. So the second helper function `getNextExit` should be able to call directly to the framework address.

For the first one, it first tries to get the `priority queue` address from `framework` and then do the call to the `priority queue` contract.

Hope this would help?

**Comment by InoMurko** [comment]
yes absolutely, thanks!
So calling 
```
getNextExit(uint256,address)
```
right after I initiated 
```
startStandardExit((uint256,bytes,bytes))
```
I get back:
`41537797034424678715388823830747088258292084671515609352316767257036339633`

which is different from what I get back from: ```getStandardExitId(bool,bytes,uint256)``` :: 1851076149135932478915228918770177426247913598

Both is size and structure...

**Comment by boolafish** [comment]
Hmm, so the two would not be same since the one you get from `getNextExit` is the priority and is different with `exitId`. However, `exitId` should be the last 160 bits of the `priority`. So you can get the exitId from priority (eg. in python),
```python
exitId = priority & ( (1<<160) - 1)
```

Well, but the one I get is indeed different from `1851076149135932478915228918770177426247913598`. Seems like this time your test is different from the original one, can you try to give a full example data that fails?

I need: `isDeposit`, `txBytes`, `utxoPos`, and the `priority` and `exitId` you get from exit game.

**Comment by boolafish** [comment]
However, I tests the exitId with the first example in description with a simplified `ExitId` contract version, it somehow resulting differently from remix:

using the following contract:
https://gist.github.com/boolafish/963f708ada0013b8ccc64ed85b6cf2fa

calling `getStandardExitId` with the following args:
- isDeposit: `true`, 
- txBytes: `0xf85b01c0f6f501f394b61a62aed0ec340ea9186f7d125466c6e31c5ff9940000000000000000000000000000000000000000880de0b6b3a764000080a00000000000000000000000000000000000000000000000000000000000000000`
- utxoPos: 2000000000

resulting: `1502227667481219919447139818364898613954005061`
and not `1373923369531234505036744913361103306032312024` from your example

Just some notes, not sure which step is causing the mismatch.

**Comment by InoMurko** [comment]
isDeposit true
utxo_pos 1000000000

txbytes:
0xf85b01c0f6f501f394f1b3595651b2b438616595a1eba4249ca9cf7263940000000000000000000000000000000000000000880de0b6b3a764000080a00000000000000000000000000000000000000000000000000000000000000000
proof: 0xf39a869f62e75cf5f0bf914688a6b289caf2049435d8e68c5c5e6d05e44913f34ed5c02d6d48c8932486c99d3ad999e5d8949dc3be3b3058cc2979690c3e3a621c792b14bf66f82af36f00f5fba7014fa0c1e2ff3c7c273bfe523c1acf67dc3f5fa080a686a5a0d05c3d4822fd54d632dc9cc04b1616046eba2ce499eb9af79f5eb949690a0404abf4cebafc7cfffa382191b7dd9e7df778581e6fb78efab35fd364c9d5dadad4569b6dd47f7feabafa3571f842434425548335ac6e690dd07168d8bc5b77979c1a6702334f529f5783f79e942fd2cd03f6e55ac2cf496e849fde9c446fab46a8d27db1e3100f275a777d385b44e3cbc045cabac9da36cae040ad516082324c96127cf29f4535eb5b7ebacfe2a1d6d3aab8ec0483d32079a859ff70f9215970a8beebb1c164c474e82438174c8eeb6fbc8cb4594b88c9448f1d40b09beaecac5b45db6e41434a122b695c5a85862d8eae40b3268f6f37e414337be38eba7ab5bbf303d01f4b7ae07fd73edc2f3be05e43948a34418a3272509c43c2811a821e5c982ba51874ac7dc9dd79a80cc2f05f6f664c9dbb2e454435137da06ce44de45532a56a3a7007a2d0c6b435f726f95104bfa6e707046fc154bae91898d03a1a0ac6f9b45e471646e2555ac79e3fe87eb1781e26f20500240c379274fe91096e60d1545a8045571fdab9b530d0d6e7e8746e78bf9f20f4e86f06


getNextExit(uint256,address) :: 41537893131890826273821685680842714587232778747829256975568515322097419631
getStandardExitId(bool,bytes,uint256) :: 459191293235409542432125961039610218394215171

**Comment by InoMurko** [comment]
OK. I have found the problem in my code:
so the way `getStandardExitId(bool,bytes,uint256)` works is not a "retrieval" but it's computed, so passing in incorrect txbytes was causing that the computation was incorrect. My txbytes were base 16 encoded. The contract didn't yield an incorrect txbytes.

fixed:
```
    data = ABI.encode("getStandardExitId(bool,bytes,uint256)", [true, Encoding.to_binary(exit_data.txbytes), exit_data.utxo_pos])
    {:ok, result} = Ethereumex.HttpClient.eth_call(%{to: exit_game_contract_address, data: Encoding.to_hex(data)})

    standard_exit_id =
      result
      |> Encoding.to_binary()
      |> ABI.TypeDecoder.decode([{:uint, 160}])
      |> hd()
```
returns `2405003940091337957725951591188881214660096633` 
which is correct, because 
priority id is `41537912114431399531400738145235197956264882478089272882835937726061818489`
and 
```
41537912114431399531400738145235197956264882478089272882835937726061818489 & ( (1<<160) - 1) =
2405003940091337957725951591188881214660096633
```

ps:
Encoding.to_binary/1 is
```
  def to_binary(hex) do
    hex
    |> String.replace_prefix("0x", "")
    |> String.upcase()
    |> Base.decode16!()
  end
```

TNX @boolafish !
