### ISSUE TITLE
Processing exits from in-flight transaction fails when the transaction has ETH and ERC20 token outputs

### ISSUE THREAD

**Issue by pgebal** [omisego/plasma-contracts#536]
## Issue Type 

```
[x ] bug report
[ ] feature request
```

## Current Behavior
Processing exits from in-flight transaction fails when the transaction has ETH and ERC20 token outputs

## Expected Behavior
Exits are successfully processed.

## Steps to Reproduce
1. Start in-flight exit from a transaction with 2 outputs: ETH and ERC20.
2. Piggyback both.
3. Call processExits twice. The second call fails.

## Suggested Fix
Change how exit game controller handles exit processor for a given exit in `enqueue` and `processExits` functions.

**Comment by boolafish** [comment]
oh.....awww, this happens since `priority` is not unique 🤦‍♂️
Nice catch. Is this found on the way of migrating python integration tests?

**Comment by pgebal** [comment]
@boolafish yes, I enabled python tests and found out that failing tests have something in common.

**Comment by boolafish** [comment]
ref, the change of removing the `nonce` into priority brings this issue: https://github.com/omisego/plasma-contracts/issues/283

Might consider to revert the change to solve the root cause if we see any non-solvable issue by the PR #537 .
