### ISSUE TITLE
Last track on contract e2e tests

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#549]
## Issue Type 

```
[ ] bug report
[x] feature request
```

## Description
We have done the python tests migrations, mostly e2e in #150 .
This issue is to have a final glance through that we have e2e tests covering the change of ALD and makes sure the gap of ALD and RootChain is tested. Potentially it can be a no work issue aside from scanning all the existing tests and makes sure it has all we need.

One thing that I am currently aware is
- new deleteIFE api. I don't think there is any e2e tests on this.

**Comment by boolafish** [comment]
## Some more tests
I draw a graph here to visualize all steps we have now: https://omisego.atlassian.net/wiki/x/JQArCw
Starting from there, I tried to think see if there are more tests possible to be covered.

### Bond related tests
I think we don't have e2e tests for the following apis: `updateStartStandardExitBondSize`, `updateStartIFEBondSize`, `updatePiggybackBondSize`.

One scenario I am particular interested is that since the update bond period (2 days) is shorter than our exit period (7 days), what would happen if the bond is update after the exit is started.

### Action pre-requisite tests
This is tests about one action can only be started after a previous action is done. eg, `piggybackInput` can only happens after `startIFE`.

Probably not worth the integration tests as it is already covered (logically) by unit tests though.

### Fee related tests
The current fee e2e tests are a bit lazy, it only tests until a fee exit (spent in payment tx) can be started.

What I really want to cover is more on whether the code can run with different tx types on eg. challenge IFE input/output. Due to our lack of tx types in our system, I think the coverage is pretty low on this.

**Comment by boolafish** [comment]
### Possible new tests on current python tests

This effort is done by scanning through existing python tests, thinking if there are sth worth testing from the introduction of ALD. (eg. tx type)

#### test_challenge_in_flight_exit_input_spent
- should fail when the challenge tx type is not allowed

#### test_challenge_in_flight_exit_not_canonical
- test the case of non-canonical due to fee input as youngest input double spent (if hard to do in python, potential doing this in js as fee e2e tests are already there)

#### test_challenge_in_flight_exit_output_spent
- should fail when the challenge tx type is not allowed

#### test_challenge_standard_exit
- should fail when the challenge tx type is not allowed

#### test_piggyback_in_flight_exit
- test piggyback with input being fee output

#### test_start_in_flight_exit
- should fail if trying to start IFE with a deposit tx

**Comment by InoMurko** [comment]
Hey @boolafish I think my work on porting end2end tests on elixir omg side might come handy!
https://github.com/omisego/elixir-omg/pull/1252
Specifically these two files:
https://github.com/omisego/elixir-omg/blob/69c99e6736b05b66b2675b26d8502f73fe47e592/priv/apps/itest/test/itest/in_flight_exits_test.exs

https://github.com/omisego/elixir-omg/blob/69c99e6736b05b66b2675b26d8502f73fe47e592/priv/apps/itest/test/features/in_flight_exits.feature

lemme know if it's useful or ... wrong :D

**Comment by boolafish** [comment]
as an outdated issue closing this :)
