### ISSUE TITLE
Create a release for the plasma contracts

### ISSUE THREAD

**Issue by thec00n** [omisego/plasma-contracts#561]
## Description 
Since both audits have wrapped up and there are at this moment no changes to contracts planned, I am proposing to create a release version for the contracts, so we can refer to this state with a specific version number.

**Comment by boolafish** [comment]
Any suggested version number? Currently we've used up to v0.2 (Rootchain.sol)
cc. @kasima

**Comment by kasima** [comment]
Let's do *v1.0*

**Comment by boolafish** [comment]
released! https://github.com/omisego/plasma-contracts/tree/v1.0.0

🎉🎊🥳🍾👏

**Comment by kasima** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/146363/72876171-7fc7ad00-3d28-11ea-8beb-9a8f37b632b6.gif)
