### ISSUE TITLE
service version

### ISSUE THREAD

**Issue by InoMurko** [omisego/plasma-contracts#568]
## Issue Type 

```
[ ] bug report
[ x] feature request
```

## Current Behavior
manual git SHA 

## Expected Behavior
a deployment would contain it's own release name

## Suggested Fix
The service design we have should allows us to independently release any of our dependency services, as long as they pass the required testing. For the sake of introspection and traceability, a particular service should propagate it's current deployed version.

I understand that at the time of deployment, we can read the git SHA and release tag from the repository and bake it into the deploy... does ALD follow a truffle migration approach and would that allow us to update a particular public variable that dependency services can read? 

Could you @kevsul and @boolafish give me some hints how to implement this ... if you find it valuable.
The requirement comes from: https://github.com/omisego/elixir-omg/issues/937#issuecomment-577663312
https://github.com/omisego/devops/issues/312#issuecomment-576198237

(tldr dropping SHA from domain name of an environment would simplify infrastructure and datadog metrics, but the information is needed anyway! services that interact with contracts would be able to expose this information by reading it contracts)

**Comment by InoMurko** [comment]
would this approach allow us to update the version from a setter?
for example when we add a new payment type (that doesn't mean we make a full contract redeploy) but just append a contract and register it.

So I guess the requirements are:
 - we follow https://semver.org/
 - set the public var in a constructor
 - provide a getter (so that external parties can read the value)
 - provide a setter so that only the contract operator can bump the version (when it adds a new payment type - ALD purpose)

Would you agree?

**Comment by boolafish** [comment]
sure. if we are having setter anyway probably we don't even need to inject from constructor?

BTW, do we really want git hash instead of some version tag? It seems more consistent with general dependency control by versioning?

**Comment by InoMurko** [comment]
Not having git hash works if what we're deploying is a release, but in a development environment, a master deploy happens more often.

**Comment by InoMurko** [comment]
One thing I've noticed is that our tag 1.0.0 release, did not bump
https://github.com/omisego/plasma-contracts/blob/v1.0.0/plasma_framework/package.json#L3
was this intentional or forgotten or we're not using this?

If we were, I could pull the version from here:
```
plasma_framework  master $ npm version
{
  plasma_framework: '0.0.1',
  npm: '6.11.3',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '35.1',
  http_parser: '2.8.0',
  icu: '64.2',
  llhttp: '1.1.4',
  modules: '72',
  napi: '4',
  nghttp2: '1.39.2',
  node: '12.10.0',
  openssl: '1.1.1c',
  tz: '2019a',
  unicode: '12.1',
  uv: '1.31.0',
  v8: '7.6.303.29-node.16',
  zlib: '1.2.11'
}
```
```
const package = require('../package.json');
await plasmaFramework.setVersion(package.version + gitsha { from: maintainerAddress });
 ```

**Comment by jbunce** [comment]
Just to clarify here: dropping the SHA from an environment would actually make things more complicated from an infrastructure point of view. We need a way to link all the components that we use to serve the applications: service accounts, database names, cluster naming etc etc. Following a pattern of `x1` `x2` etc does not make it clear which resource is used for which deployment.

**Comment by jbunce** [comment]
in addition, the naming of some components that we use are constrained by a maximum naming length. So a contract SHA allows us to be deterministic about where the resource is in use while still complying with naming standards.

**Comment by kevsul** [comment]
> I guess the TLDR question in this comment is: what does the version in package.json represent? 

It's the version of the `plasma_framework` NPM package if such a thing existed, which is doesn't. We're not currently using it, but we could if it's helpful.

I'm in favour of using Semver, because it's immediately obvious that `1.1.0` is newer than `1.0.0`.
Semver allows you to add the git SHA as a build metadata e.g. `1.0.0+a1d16cc`
@jbunce does that work?

**Comment by boolafish** [comment]
Is this issue done as your PR getting merged? @InoMurko 

And also, is the version schema debate....finalized?XD

**Comment by kevsul** [comment]
> Is this issue done as your PR getting merged? @InoMurko
> 
> And also, is the version schema debate....finalized?XD @jbunce

I think that's a 'yes' @boolafish 😄
