### ISSUE TITLE
blknum vs blockNumber in event emmited

### ISSUE THREAD

**Issue by InoMurko** [omisego/plasma-contracts#575]
https://github.com/omisego/plasma-contracts/blob/bcc2de4286d7cfbf1152e779a787981b1cb8ecf9/plasma_framework/contracts/src/framework/BlockController.sol#L27

Is there a specific reason why this is called blockNumber and not blknum, as in other events?

I have noticed that blknum  and blockNumber are used in the codebase. is their a simple answer to what it should be and we make a find and replace?

https://github.com/omisego/plasma-contracts/blob/master/plasma_framework/docs/integration-docs/integration-doc.md
blockNumber appears 4 times
blknum appears 5 times

can we unify this under blknum?

**Comment by boolafish** [comment]
I don't think there is a specific reason of naming. If we've decide our global naming glossory we can try to be consistent and make the change.

**Comment by InoMurko** [comment]
yolo, done
