### ISSUE TITLE
Upgrade truffle to newer version

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#592]
## Description
Seems like truffle new release [5.1.15](https://github.com/trufflesuite/truffle/releases/tag/v5.1.15?utm_campaign=Built%20with%20Truffle&utm_source=hs_email&utm_medium=email&utm_content=84023637&_hsenc=p2ANqtz-8VD5nB54mLkQuL8aKkZAAWhGE6a4IWFR9Nvc6f2Ty6lAMA_ljIesWEy4qS9R8jDXZhdP4lWpU1vVEywhEyo1J1n9h6bA&_hsmi=84023637) might solve the previous unstable migration issue:

In this PR: https://github.com/trufflesuite/truffle/pull/2808 of the change log, it claims to solve: https://github.com/trufflesuite/truffle/issues/2257

Should give it a try and make our DevOps happy 😛

**Comment by jbunce** [comment]
This would make contract deployments less expensive!

**Comment by arthurk** [comment]
Currently we have many failures due to the issue and it's costing us many ETH for re-trying the deployments. Is there any way we can try the new version?
