### ISSUE TITLE
[fast exits] Research on token type that could be used to encapsulate 

### ISSUE THREAD

**Issue by pik694** [omisego/plasma-contracts#621]
## Issue Type 

```
[ ] bug report
[x] feature request
```

# Description
The task is to go through common Ethereum token standards and choose a one which suits best for wrapping a Plasma SE.

**Comment by pik694** [comment]
# Rationale
As OmiseGO, we are seeking a method of fast exits, which can be done be a simple mechanism of locking a plasma exit in a non-fungible token,
which can then be sold and once the exit is processed, the owner of the token can burn the token and receive the value from the exit.

The initial work can be found here: [https://github.com/omisego/research/blob/master/plasma/simple_fast_withdrawals.md](https://github.com/omisego/research/blob/master/plasma/simple_fast_withdrawals.md)

As a part of the research, we have to choose a token standard, that would suit best our needs - we are limiting ourselves to the currently existing and common standards.

## ERC-721
This standards seems to be a good default.
One could create an NFT, that could be then further transferred to any other user.
The standard is widely used and had been specified in order to track and transfer distinguishable goods, ex. virtual collectables.
The token wraps the exit and the value underneath can be transferred once the exit has been processed.

## ERC-1155
This standard is newer and not that commonly used, but is superior in one aspect: wrapping an exit into a ERC-1155 token, would allow the owner of the token to sell just a part of if,
or sell it to many users. This feature may be pleasant when a users wants to trade the exit on a market.
To provide such a mechanism, the liquidity contract would mint a new token - representing an exit, and the minted amount would equal to the amount of the tokens from the exit.
Ex. Alice wants to exit 10 Eth from Plasma via liquidity contract, the contract starts the exit on behalf of Alice, mints an unique token in amount of 10 * 10^18. 
Alice can then sell/transfer any amount of the token - in this case 1 token represents 1 wei stored in the exit.

## Additional features
No matter which standard we stick to, we can add some extra convenience features to the contract itself.

One of the features may be a built-in atomic swap mechanism, 
that would enable users to trade an NFT-locked exit without need for any other proxies.

## Further considerations on liquidity contract specification
The main requirement of the liquidity contract is to wrap a plasma exit in some token and allow the transfers of the wrapping token.
Once the plasma exit is mature and has been processed, the owner of the wrapping, should be able to burn it and receive the funds that had been wrapped.

By the design, all funds that would be sent to the liquidity contract are stored on the same Etehereum address (the contract's address) - it is very similar Plasma Framework Vaults.
Therefore, it is very important to create a mechanism, that would allow the owner of the wrapping token to burn the token no earlier 
then the exit is actually processed (and wrapped value is sent to the liquidity contract); or in case of burning too early, no funds would be transferred.

**Comment by whoisjeremylam** [comment]
Would it be possible to list a few pros and cons? Is ERC-721 the recommendation?

**Comment by pik694** [comment]
## ERC721
### Pros
- commonly used
- probably slightly cheaper
### Cons
- little less mighty 
 
## ERC1155
### Pros
- allows for lending from multiple users and having all the loans collateralised by just one plasma exit
- allows for making loan and collateralising it with just a part of the exit (10 Eth worth exit, and loan that is backed up by just 2 Eth from the exit - the other 8 will return to the owner once the exit is processed)
### Cons
- higher gas usage
- less commonly used
- (probably less support from wallets etc)


I really like the option to trade parts of the value wrapped. In my opinion ERC1155 is a little bit more interesting to work with and gives a little more possibilities - but this comes at a price.

**Comment by pik694** [comment]
The decision was made to proceed with ERC721, as this is a default option, and we are not sure whether we need ERC1155 features at this moment.
