### ISSUE TITLE
[fast exits] Start standard exit from a another contract

### ISSUE THREAD

**Issue by pik694** [omisego/plasma-contracts#623]
## Issue Type 

```
[ ] bug report
[x] feature request
```

# Description 
Let's make some tests on starting a SE by a liquidity contract LC. 

The flow should be as following:
1. Alice transfers some value to LC  (utxo0);
1. Alice sends an Ethereum tx to LC with some proof.
1. LC starts a SE on Plasma Framework contracts with the proofs provided by Alice.
1. Required time passes.
1. Alice processes exit queue -> LC receives the funds.

## Additional requirements
- [ ] only the user that transferred the amount to LC can start the SE via LC.

**Comment by conniemkwan** [comment]
Sorry @pik694 I accidentially closed it but have reverted it back to Review.

**Comment by pik694** [comment]
@conniemkwan no problem :slightly_smiling_face:
