### ISSUE TITLE
Processing in-flight exits that are not piggybacked returns with error

### ISSUE THREAD

**Issue by pgebal** [omisego/plasma-contracts#73]
## Issue Type 

```
[x] bug report
[ ] feature request
```

## Current Behavior
When there is an in-flight exit that is not piggybacked by anyone, processExits function call returns with error.

## Steps to Reproduce

1. Checkout ce4a23d75b8c5f9cc4526f50bde4968908fc258d
2. Comment out line 200 in test_start_in_flight_exit.py
3. Run tests

**Comment by boolafish** [comment]
It seems like the reason is that in `startInflightExit` we didn't put the in-flight-exit into the queue.
`_enqueueExit(...)` is only called on piggyback.

**Comment by paulperegud** [comment]
> It seems like the reason is that in `startInflightExit` we didn't put the in-flight-exit into the queue.
> `_enqueueExit(...)` is only called on piggyback.

This is behavior as expected. IFE may contain many tokens and token queues need to be processed independently because of security reasons (attacking tokens, badly implemented tokens).
