### ISSUE TITLE
Contract should be able to support ERC20 without return value

### ISSUE THREAD

**Issue by boolafish** [omisego/plasma-contracts#95]
## Issue Type 
As OMG contract is implemented in a way that does not return "true" when transfer, as we want to be able to support OMG token, our contract need to support ERC20 `transferFrom` function without a return value.

For details, see this: https://medium.com/coinmonks/missing-return-value-bug-at-least-130-tokens-affected-d67bf08521ca

```
[ ] bug report
[x] feature request
```

## Current Behavior
In ` function depositFrom(bytes _depositTx)`

```
// Warning, check your ERC20 implementation. TransferFrom should return bool
require(ERC20(decodedTx.outputs[0].token).transferFrom(msg.sender, address(this), decodedTx.outputs[0].amount));
```

## Expected Behavior
Does not need the `transferFrom` to return bool.

## Suggested Fix
Perhaps use `address.call` directly, and in solidity 0.5, it returns success or failed + return value. We can rely on the result of "success" or "failed' directly instead.

Or the article above (in Issue Type) do provide some wrapper example code as well.

## Motivation for Change
To support OMG token

**Comment by pdobacz** [comment]
Hi, this is a fair request, assuming that the affected tokens don't migrate to their fixed versions. However, note that there have been some preliminary steps taken to fix this issue for OMG. I don't know what is the status of this effort now.
