### ISSUE TITLE
Support chain_id parameter in contract code

### ISSUE THREAD

**Issue by pnowosie** [omisego/plasma-contracts#98]
Extend ECRecover lib to support chain_id in signature verification. Also try to pass its value at deployment time.
Needed to fully support EIP-712 signing.

This is described in [EIP-155 Simple replay attack prevention](http://eips.ethereum.org/EIPS/eip-155)

**Comment by kevsul** [comment]
From EIP-712:
> Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.

I believe chainId does not make sense in our case.
Also, I've confirmed that Metamask will happily sign when there is no chainId present.

**Comment by pnowosie** [comment]
For a record of conversation in Slack in the topic

@kevsul: I mentioned this before somewhere - is the chain_id necessary at all? As you mentioned, our transactions are on the childchain, and have nothing to do with which rootchain we’re on, right?

@pdobacz: for posterity - not necessary, as long as the contract address tells those child chains (on different rootchains) apart. For this to hold, the contract addresses just need to be deployed by distinct addresses.

@pnowosie: Specs says that members of Eip712Domain are optional
> EIP712Domain with one or more of the below fields. Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.

@kevsul: I’ve confirmed that MetaMask works with no chainId

**Comment by pnowosie** [comment]
To summarize above:
* `chainid` is not required neither by EIP-712 nor MetaMask
* we can achieve replay prevention using different deploying addresses on different Ethereum networks
* supporting `chainid` would significantly complicate contract deployment (value of chainid would need to be pass to the contract during deployment).

Considering above points I'm opting to reject this task. 

Further work enabling contract address verification in structural sigs is held in omisego/elixir-omg#621

**Comment by pnowosie** [comment]
@Pongch - I think I'll track the remaining work in omisego/elixir-omg#621 
Would you like this task be closed now or as a completion of :point_up: ##621 :question:

**Comment by Pongch** [comment]
@pnowosie lets close now. If `chain_id` is not required in 712 and transaction signing works fine on metamask 👍
